### PR TITLE
[Common] Use size-neutral types.

### PR DESCRIPTION
**Pull request by cxd4**
Somewhat (but not really) related to https://github.com/project64/project64/pull/728 .

Here, again, `int32_t` is a completely random and arbitrary preference of parameter type, as the relevant functions have no pertinence to the necessity of having 32-bit precision (let alone exactly that).

What happens if you're compiling for a system whose `Sleep()` function equivalent, for example, only accepts a 64-bit (or a 21-bit, or 16-bit) unsigned integer for the timeout counter in milliseconds?  This choice of `uint32_t` is still partly biased to the Windows `Sleep()` function and is not really portable.

A better choice would be the neutral type `unsigned long`, but `size_t` would be understandable.

### CODE REVIEW

**Comment by project64** [comment]
in which case i will use a #define to handle the different os, I prefer standard types where possible over say unsigned long, now I do not mind size_t caus it is not fixed between 32bit and 64bit and want the value changed, not so much here.

**Comment by cxd4** [comment]
>now I do not mind size_t caus it is not fixed between 32bit and 64bit and want the value changed, not so much here.

What does that mean?  You want the value changed "not so much here", or that you would rather use `size_t` over standard types such as `unsigned long`?

>in which case i will use a #define to handle the different os

If the different os has a Sleep() function, then just call Sleep() without macros like #ifdef WIN32 Sleep(uint32_t) #elif ... Sleep(uint64_t) #elif ... Sleep(uint16_t) ... it should just be a standard type like unsigned int/long that is not fixed between 32-bit and 64-bit, like uint32_t is.

**Comment by project64** [comment]
well I doubt sleep value is ever over a 32bit value anyway ... I was more refering to size_t works better in for 32/64 builds since it will act different

**Comment by cxd4** [comment]
Which is why, in this case, I'm not sure whether you prefer `size_t` or `unsigned long`.

Either one acts different in 32- and 64-bit builds (as `size_t` usually typedef'd to an `unsigned long` anyway, except on Windows), so either one is an improvement over `uint32_t`, which has very little to do with milliseconds or Sleep interval precisions because 32 bits is irrelevant to Physics class.

The only reason I can think of for making it a `uint32_t` is if the MIPS hardware has a 32-bit limit on what the timer for sleeping can be or something, even though it has 64-bit registers.  Other than that, why uint32?

>well I doubt sleep value is ever over a 32bit value anyway

For the sake of not arguing this, I'll assume nobody will care to allow > 32-bit time units / inputs.

If it's *under* a 32-bit value, you would still have to #ifdef inside the function to decide how to convert the uint32_t into a uint16_t or whatever anyway.  This would be no different if the source was a 32-, 64-, 48-, 57-, etc.-bit `unsigned long` of whatever width.  The difference is that `sizeof(unsigned long) >= sizeof(uint32_t)`, so the `long` has a greater chance of not losing information than the uint32_t does.

**Comment by cxd4** [comment]
*burp*

**Pull request closed without merging**
