### PR TITLE
[64DD] Updated 64DD emulation

### PR DESCRIPTION
**Pull request by LuigiBlood**
Basically, the main changes are:
- Removes the dependence to MAME format internally (no more conversion)
  - Now supports SDK & D64 format natively via LBAToPhys & LBAToByte (rewritten libleo functions)
- CN64Disk handles Disk access calculations, now performs heuristics to find proper System Data and Disk ID in case of errors.
- Handles all 64DD IPLs seperately (JP disk with JP IPL, US disk with US IPL, Dev disk with Dev IPL).
- Performs custom CRC calculations for disks, to differenciate them properly.
  - RDB is updated as a result.
- Add "64DD" tab in Settings.
  - Handles IPL file paths and save type.
- Supports alternate save format that only saves RAM Area (smaller, now default).
  - Shadow files are still supported and taken as priority if Shadow File is found.
  - D64 Shadow File will have fully expanded RAM Area if smaller or not present.

**It's not very tested. I gotta say. I may push random bugfixes from time to time.**

### CODE REVIEW

**Comment by project64** [comment]
is this fine to merge?

**Comment by LuigiBlood** [comment]
huge bug found

**Comment by LuigiBlood** [comment]
Question, when loading a ROM + disk combo (such as F-Zero X + Expansion Kit disk), do you want the settings from a base ROM to be loaded, or the settings from the disk to be loaded?

**Comment by Fanatic-64** [comment]
Chiming in on the above, perhaps a setting could be included under a disk's entry to specify whether it's settings should override those of a base ROM? Something like OverrideBaseROMSettings=1/Yes or 0/No.

**Comment by LuigiBlood** [comment]
For now the default is load from disk. I was suggested the idea of taking the base ROM settings and then have the settings of the Disk on top, but it's pretty difficult to implement properly.

**Comment by LuigiBlood** [comment]
Putting aside the problem of configuration for combo ROM + Disk games, what it looks like to me is that it seems to work just fine for the most part.

**Comment by LuigiBlood** [comment]
I think this is mergeable. I didn't find big issues when I messed around.

**Comment by oddMLan** [comment]
@project64

**Pull request merged**
