### PR TITLE
Resident Evil 2 rdb fixes

### PR DESCRIPTION
**Pull request by Lithium64**
Changed back RDRAM to 4, if set to 8 will cause resolution issues with Glide64

### CODE REVIEW

**Comment by AmbientMalice** [comment]
I was wary of setting it to 8MB to begin with. Hopefully GLideN64 will handle the game properly.

**Comment by AmbientMalice** [comment]
Out of curiosity, what do you mean by "resolution issues"? I have noticed that the screen flashes with garbage between camera angle changes more often and more noticably with 8MB compared to 4MB.

**Comment by Lithium64** [comment]
@AmbientMalice Resolution issues like these

glide64_resident_evil_ii_01
glide64_resident_evil_ii_02
glide64_resident_evil_ii_03
glide64_resident_evil_ii_04

**Comment by AmbientMalice** [comment]
I see. Thanks for the explanation.

**Pull request merged**
