### PR TITLE
Visual studio2013 fix

### PR DESCRIPTION
**Pull request by death-droid**
Allows Visual studio 2013 to successfully compile, same as previous commit but split it into a branch so i can still submit other changes.

### CODE REVIEW

**Comment by death-droid** [comment]
@project64 if you could get to checking out these soon! That would be great!

**Comment by project64** [comment]
I created a branch called VS2013, does this branch work for you now?

I need to double check that I did not break anything on 2008 but as long as I haven't and you are happy I will merge that branch and close this pull request.

**Comment by death-droid** [comment]
I can confirm your branch works perfectly :) Definitely has my tick of approval!

**Comment by project64** [comment]
ok merged my branch, should work correct in vs2013 now

**Pull request closed without merging**
