### PR TITLE
Create Korean.pj.Lang

### PR DESCRIPTION
**Pull request by GagnonJung**
[Add description of the PR here]

Fixes #

### Proposed changes
  - Korean language support

### CODE REVIEW

**Comment by Jj0YzL5nvJ** [comment]
Wrong codification,the correct one is `Windows CR LF` + `UTF-8 BOM`.

To fix, you can use `git reset --hard 7917fb671d54078228fb01045a8fc375d6f0a550`.
After re-adding the corrected file, use `git push --force origin patch-1`.

**Comment by GagnonJung** [comment]
> Wrong codification,the correct one is `Windows CR LF` + `UTF-8 BOM`.
> 
> To fix, you can use `git reset --hard 7917fb671d54078228fb01045a8fc375d6f0a550`.
> After re-adding the corrected file, use `git push --force origin patch-1`.

Sorry, I didn't check this. I'll care about it next time.

**Comment by GagnonJung** [comment]
@Jj0YzL5nvJ 

Sorry, I didn't check this. I'll care about it next time.

**Comment by Jj0YzL5nvJ** [comment]
Fixed by 5ef0bad6c85c4f7a8e1ff5d1435db897db0e7151

**Pull request merged**
