### PR TITLE
disable some trying to store XXXXXXXX error

### PR DESCRIPTION
**Pull request by Nekokabu**

### CODE REVIEW

**Comment by vgturtle127** [comment]
@Nekokabu What does this fix, exactly?

**Comment by vgturtle127** [comment]
@project64 Wait, what did it fix? :laughing:

**Comment by project64** [comment]
no idea if it fixes anything, but if it is occurring then it will reduce the popup messages shown when debugger is enabled

**Comment by vgturtle127** [comment]
@project64 Oh, OK. I thought this was some emulation error, and I got confused. :blush:

**Pull request merged**
