### PR TITLE
WIP DL/s and VI/s Together

### PR DESCRIPTION
**Pull request by theboy181**
I don't expect this to get PR approved, but I was hoping that other could look at it and see if they could improve the code.

This show the minor changes that were needed to add the option to the settings menu and actually displays to the DL/s and VI/s together, only the calculations for the DL/s and VI/s don't work when FPS limit is off.

I was only able to get the DL's to show in the bottom right hand of the screen because I was not able to create a new pane in the status bar. If anyone is able to lend me some advice I would appreciate it very much..

Thanks

### CODE REVIEW

**Comment by vgturtle127** [comment]
@theboy181 So this just displays both at the same time? That seems useful to me, why don't you update from master?

What does @project64 @cxd4 @LegendOfDragoon @AmbientMalice @Frank-74 @Fanatic-64 @purplemarshmallow @tony971 think of this?

Personally, I wish we could have the percentage of speed on there too, but then again I am a bit of a whore for numbers flashing all over the screen when I am testing. :wink:

**Comment by theboy181** [comment]
I would love to have this adds to master. However there is an issue with the code and the numbers break in certain situations. I think when the internal rom changes FPS the counter gets stuck. I brought this up with zilmar and he said he may have a look when he has time. 

He is very busy with his android goals right now.

**Comment by vgturtle127** [comment]
@theboy181 OK, just curious. :smile: 

It is a pretty big goal to port Project64 to Android. Although, wouldn't Linux be easier? I would think so...

**Comment by project64** [comment]
https://github.com/project64/project64/commit/4733420dfa0f18501ea710964c1b35c8f3f129d6

what do you think?

**Comment by theboy181** [comment]
Drool!  Thank you!!!!

Sent from my iPhone

On Aug 10, 2016, at 3:06 AM, zilmar <notifications@github.com<mailto:notifications@github.com>> wrote:


4733420<https://github.com/project64/project64/commit/4733420dfa0f18501ea710964c1b35c8f3f129d6>

what do you think?

-

**Comment by cxd4** [comment]
That seems useful to me.  Why don't you pull from master and close if you like the changes?

What does @project64 @cxd4 @LegendOfDragoon @AmbientMalice @Frank-74 @Fanatic-64 @purplemarshmallow @tony971 @vgturtle127 @theboy181 @allthen64devs think of this?

**Comment by project64** [comment]
@theboy181 does that mean I can close this now

**Comment by theboy181** [comment]
please, I love it and thank you.. this makes my first world issues with PJ64 emulation disappear!

**Pull request closed without merging**
