### PR TITLE
enabled Fixed Audio=1, for Aidyn Chronicles - The First Mage (U)[!](v1.0)

### PR DESCRIPTION
**Pull request by MelchiorGaspar**
Aidyn Chronicles - The First Mage (U)[!](v1.0)
- Advanced Block Linking
enabled o disabled, it crashes except its not quite a crash

I took another look at settings and got it to not crash by enabling
Fixed Audio Timing
Fixed Audio=1

fixes the rom's internal crash screen (black w/ yellow text)
it sounds terrible but runs, the usual menu severe stutter is still there

### CODE REVIEW

**Comment by death-droid** [comment]
"is this how I get update to my fork from master?"
Nooooooooooooooooooooooooooooooooooooooooooope

https://help.github.com/articles/syncing-a-fork/

Otherwise you end up littering the master project with pull requests in the commits

**Comment by MelchiorGaspar** [comment]
loi ;^_^; thx death-droid, you deserve a hug  ;D 

so how do I go about cleaning up the mess I am making ;D?

**Comment by dsx-** [comment]
can't seem to reproduce this crash

**Comment by MelchiorGaspar** [comment]
I am using the up  to date rdb file
this is what I get if Fixed Audio is off....
pj64_aidyncrash_fixedaudio-off_

how can I get you a copy of my config file...?
whats your system specs?

**Comment by MelchiorGaspar** [comment]
pj64_glide64_settings_

**Pull request merged**
