### PR TITLE
Remove the wait time to close the support window

### PR DESCRIPTION
**Pull request by LordEnma**
This PR would removes the ridiculous wait time to close the support window from the emulator. Ignoring the fact that the code to remove it is literally in the source code, other emulators like yuzu make thousands of dollars a month without a support screen that forces you to wait to start the emulator

### Does this make breaking changes?

I do not believe so.

### Does this version of Project64 compile and run without issue?

I have not tested this yet, since i can't figure out how to build my fork under linux or windows

### CODE REVIEW

**Comment by Squall-Leonhart** [comment]
Rejected, you're not welcome.

**Comment by LordEnma** [comment]
Why? Isn't this project open source? It is open to numerous conflicting ideas. If you just blindly reject an idea like you have, then you clearly don't understand the spirit of open source software

**Comment by Squall-Leonhart** [comment]
*Holds up a mirror*

**Comment by LordEnma** [comment]
> _Holds up a mirror_

What? Lmao is that all you have for an argument🤣

**Comment by LordEnma** [comment]
> Rejected, you're not welcome.

Why? Isn't this project open source? It is open to numerous conflicting ideas. If you just blindly reject an idea like you have, then you clearly don't understand the spirit of open source software

**Comment by PowerPlayPone** [comment]
Just give them money. It's not that hard. I did. Why would you not want to give project64 more money to work on future versions?

**Comment by LordEnma** [comment]
> Just give them money. It's not that hard. I did. Why would you not want to give project64 more money to work on future versions?

You shouldn't release a worse product for people who don't pay for your FREE SOFTWARE that is openly advertised as such. And if this truly were the case, they why is yuzu making thousands a month without a stupid window begging for money?

And I'm not even opposed to a window that offers a link to donate, it's the fact that it forces people to wait to use the emulator is why I'm proposing to remove it

**Comment by PowerPlayPone** [comment]
> > Just give them money. It's not that hard. I did. Why would you not want to give project64 more money to work on future versions?
> 
> You shouldn't release a worse product if people don't pay for your FREE SOFTWARE that is openly advertised as such. And if this truly were the case, they why is yuzu making thousands a month without a stupid window begging for money?

NGL, you're probably gonna get banned if you keep acting like this.

if you want to have a better product, pay.

**Comment by LordEnma** [comment]
> > > Just give them money. It's not that hard. I did. Why would you not want to give project64 more money to work on future versions?
> > 
> > 
> > You shouldn't release a worse product if people don't pay for your FREE SOFTWARE that is openly advertised as such. And if this truly were the case, they why is yuzu making thousands a month without a stupid window begging for money?
> 
> NGL, you're probably gonna get banned if you keep acting like this.
> 
> if you want to have a better product, pay.

So why doesn't yuzu have a window asking for donations that has you wait to use the emulator if you don't? Genuine question

**Comment by PowerPlayPone** [comment]
> > > > Just give them money. It's not that hard. I did. Why would you not want to give project64 more money to work on future versions?
> > > 
> > > 
> > > You shouldn't release a worse product if people don't pay for your FREE SOFTWARE that is openly advertised as such. And if this truly were the case, they why is yuzu making thousands a month without a stupid window begging for money?
> > 
> > 
> > NGL, you're probably gonna get banned if you keep acting like this.
> > if you want to have a better product, pay.
> 
> So why doesn't yuzu have a window asking for donations that has you wait to use the emulator if you don't? Genuine question

You can't even be bothered to wait 30 seconds?

**Comment by LordEnma** [comment]
> > > > > Just give them money. It's not that hard. I did. Why would you not want to give project64 more money to work on future versions?
> > > > 
> > > > 
> > > > You shouldn't release a worse product if people don't pay for your FREE SOFTWARE that is openly advertised as such. And if this truly were the case, they why is yuzu making thousands a month without a stupid window begging for money?
> > > 
> > > 
> > > NGL, you're probably gonna get banned if you keep acting like this.
> > > if you want to have a better product, pay.
> > 
> > 
> > So why doesn't yuzu have a window asking for donations that has you wait to use the emulator if you don't? Genuine question
> 
> You can't even be bothered to wait 30 seconds?

**Comment by LordEnma** [comment]
> > > > > Just give them money. It's not that hard. I did. Why would you not want to give project64 more money to work on future versions?
> > > > 
> > > > 
> > > > You shouldn't release a worse product if people don't pay for your FREE SOFTWARE that is openly advertised as such. And if this truly were the case, they why is yuzu making thousands a month without a stupid window begging for money?
> > > 
> > > 
> > > NGL, you're probably gonna get banned if you keep acting like this.
> > > if you want to have a better product, pay.
> > 
> > 
> > So why doesn't yuzu have a window asking for donations that has you wait to use the emulator if you don't? Genuine question
> 
> You can't even be bothered to wait 30 seconds?

I didn't know fast respond times were a bad thing here. So will answer the question?

**Comment by GodOf-Thunder** [comment]
LordEnma

You are fighting a losing battle. Just fork the source code and offer it to people who feel as you do.

**Comment by TheGent** [comment]
> LordEnma
> 
> You are fighting a losing battle. Just fork the source code and offer it to people who feel as you do.

I am inclined to agree with [GodOf-Thunder](https://github.com/GodOf-Thunder) here, or at least introduce the function that once a user has donated, payed, disable the wait timer so they no longer have to wait for 30 seconds. I do not believe they should have to keep seeing the screen in the chance they might want to pay again? or am I alone in this assumption? So the best solution would be to disable the pop up screen if user has donated, payed (however you would like to say it)

**Comment by Fanatic-64** [comment]
> > LordEnma
> > You are fighting a losing battle. Just fork the source code and offer it to people who feel as you do.
> 
> I am inclined to agree with [GodOf-Thunder](https://github.com/GodOf-Thunder) here, or at least introduce the function that once a user has donated, payed, disable the wait timer so they no longer have to wait for 30 seconds. I do not believe they should have to keep seeing the screen in the chance they might want to pay again? or am I alone in this assumption? So the best solution would be to disable the pop up screen if user has donated, payed (however you would like to say it)

The message is disabled once the user has donated and entered a code that gets sent to them. It's always been like this.

**Comment by LordEnma** [comment]
> LordEnma
> 
> You are fighting a losing battle. Just fork the source code and offer it to people who feel as you do

This is an open source project, where anyone can contribute, and I feel like this change would be better in the main branch where everyone can benefit, not in the sea of forks. Your argument goes against the core principles of open source software

**Comment by LordEnma** [comment]
> > > LordEnma
> > > You are fighting a losing battle. Just fork the source code and offer it to people who feel as you do.
> > 
> > 
> > I am inclined to agree with [GodOf-Thunder](https://github.com/GodOf-Thunder) here, or at least introduce the function that once a user has donated, payed, disable the wait timer so they no longer have to wait for 30 seconds. I do not believe they should have to keep seeing the screen in the chance they might want to pay again? or am I alone in this assumption? So the best solution would be to disable the pop up screen if user has donated, payed (however you would like to say it)
> 
> The message is disabled once the user has donated and entered a code that gets sent to them. It's always been like this.


> > > LordEnma
> > > You are fighting a losing battle. Just fork the source code and offer it to people who feel as you do.
> > 
> > 
> > I am inclined to agree with [GodOf-Thunder](https://github.com/GodOf-Thunder) here, or at least introduce the function that once a user has donated, payed, disable the wait timer so they no longer have to wait for 30 seconds. I do not believe they should have to keep seeing the screen in the chance they might want to pay again? or am I alone in this assumption? So the best solution would be to disable the pop up screen if user has donated, payed (however you would like to say it)
> 
> The message is disabled once the user has donated and entered a code that gets sent to them. It's always been like this.

So you support paid quality of live improvements that remove nagware from software that advertises itself as an equal experience if you donate or choose not to?

**Comment by flagrama** [comment]
> So why doesn't yuzu have a window asking for donations that has you wait to use the emulator if you don't? Genuine question

The honest answer is that yuzu has plenty of volunteers who actually contribute, while Project 64 has primarily been all Zilmar's work for quite a while now with small contributions by a few other people. If there were other developers who did the same amount of work as Zilmar has there would be an argument for removing it. As it is, it's open source by definition, but Zilmar's hard work in practice and he deserves to be compensated for it.

**Comment by dstreta47** [comment]
It doesn't. I understand that you want to advocate for a better product but since it is open source, the user still has the right to modify the source as they want and compile it. But expecting to outright remove all messages that asks for donation is cruel to developers who don't have much incentive to work on this apart from the small contribution people make either in spirit of open source or became they can't be bothered to compile the source themselves. It isn't meant to target anyone.

**Comment by LordEnma** [comment]
> It doesn't. I understand that you want to advocate for a better product but since it is open source, the user still has the right to modify the source as they want and compile it. But expecting to outright remove all messages that asks for donation is cruel to developers who don't have much incentive to work on this apart from the small contribution people make either in spirit of open source or became they can't be bothered to compile the source themselves. It isn't meant to target anyone.

I'm not opposed to messages linking to donation pages, I'm just opposed to the wait time being there at all, it just seems like nagware

**Comment by TheGent** [comment]
> > > LordEnma
> > > You are fighting a losing battle. Just fork the source code and offer it to people who feel as you do.
> > 
> > 
> > I am inclined to agree with [GodOf-Thunder](https://github.com/GodOf-Thunder) here, or at least introduce the function that once a user has donated, payed, disable the wait timer so they no longer have to wait for 30 seconds. I do not believe they should have to keep seeing the screen in the chance they might want to pay again? or am I alone in this assumption? So the best solution would be to disable the pop up screen if user has donated, payed (however you would like to say it)
> 
> The message is disabled once the user has donated and entered a code that gets sent to them. It's always been like this.

I thought the pop up still occurs on the off chance a user wants to donate, pay again? just does not make you wait? I will be honest i do not us the project, but i do remember when i tried it, that the screen still appears once wait timer was disabled.

**Comment by flagrama** [comment]
I'm pretty sure at least in the current iteration it goes away.

**Comment by GodOf-Thunder** [comment]
> > > > LordEnma
> > > > You are fighting a losing battle. Just fork the source code and offer it to people who feel as you do.
> > > 
> > > 
> > > I am inclined to agree with [GodOf-Thunder](https://github.com/GodOf-Thunder) here, or at least introduce the function that once a user has donated, payed, disable the wait timer so they no longer have to wait for 30 seconds. I do not believe they should have to keep seeing the screen in the chance they might want to pay again? or am I alone in this assumption? So the best solution would be to disable the pop up screen if user has donated, payed (however you would like to say it)
> > 
> > 
> > The message is disabled once the user has donated and entered a code that gets sent to them. It's always been like this.
> 
> I thought the pop up still occurs on the off chance a user wants to donate, pay again? just does not make you wait? I will be honest i do not us the project, but i do remember when i tried it, that the screen still appears once wait timer was disabled.

I am not opposed to asking for donations. I am opposed to being punished for not donating to the project. especially when it crashes so often.

**Comment by flagrama** [comment]
The stable version shouldn't crash that often. The dev version is in the middle of a major accuracy re-work, so things breaking here and there is expected. Once the work is finally done even the stuff that does crash on stable should stop, though using interpreter there shouldn't be much with that issue on stable in the first place.

You are free to use ares, mupen64plus, or the myriad of other options available for n64 emulation if the nag screen bothers you that much.

**Comment by GodOf-Thunder** [comment]
> The stable version shouldn't crash that often. The dev version is in the middle of a major accuracy re-work, so things breaking here and there is expected. Once the work is finally done even the stuff that does crash on stable should stop, though using interpreter there shouldn't be much with that issue on stable in the first place.
> 
> You are free to use ares, mupen64plus, or the myriad of other options available for n64 emulation if the nag screen bothers you that much.

I prefer Project64 Legacy myself. Or even 1964.

**Comment by LordEnma** [comment]
> The stable version shouldn't crash that often. The dev version is in the middle of a major accuracy re-work, so things breaking here and there is expected. Once the work is finally done even the stuff that does crash on stable should stop, though using interpreter there shouldn't be much with that issue on stable in the first place.
> 
> You are free to use ares, mupen64plus, or the myriad of other options available for n64 emulation if the nag screen bothers you that much.

I want all emulators to be improved, not just ones that I dont use because they are inferior.

**Comment by flagrama** [comment]
Then put in the actual work for it. Depriving one of the developers of compensation for all the work they do in one of the emulators isn't going to help, it'll just make them stop working on it and it will die since there aren't other contributors doint the work they are doing. And even removing the timer will affect that because people will just skip the pop-up if there is no timer for it.

**Comment by LordEnma** [comment]
> Then put in the actual work for it. Depriving one of the developers of compensation for all the work they do in one of the emulators isn't going to help, it'll just make them stop working on it and it will die since there aren't other contributors doint the work they are doing. And even removing the timer will affect that because people will just skip the pop-up if there is no timer for it.

That is the sacrifice you make when you release software for free. Welcome to the internet

**Comment by flagrama** [comment]
It isn't. You wouldn't have this PR up if it was. Welcome to the real world.

**Comment by LordEnma** [comment]
> It isn't. You wouldn't have this PR up if it was. Welcome to the real world.

So why do thousands of pieces of free software that has had years of hard work put into it by a small group of people or even one person, not have wait times on their donations windows, if they even have them at all? Use your brain

**Comment by GodOf-Thunder** [comment]
> Then put in the actual work for it. Depriving one of the developers of compensation for all the work they do in one of the emulators isn't going to help, it'll just make them stop working on it and it will die since there aren't other contributors doint the work they are doing. And even removing the timer will affect that because people will just skip the pop-up if there is no timer for it.

It is free or it isn't free. With this nag screen it is not free. This isn't please donate to this project. It is pay up or we will nag you to death.

**Comment by flagrama** [comment]
Because they chose not to.

**Comment by LordEnma** [comment]
> Because they chose not to.

So we can choose to not have it here

**Comment by TheGent** [comment]
> > Then put in the actual work for it. Depriving one of the developers of compensation for all the work they do in one of the emulators isn't going to help, it'll just make them stop working on it and it will die since there aren't other contributors doint the work they are doing. And even removing the timer will affect that because people will just skip the pop-up if there is no timer for it.
> 
> That is the sacrifice you make when you release software for free. Welcome to the internet

Ok now that isn't the attitude [LordEnma](https://github.com/LordEnma), If  the Author wants a support window they are entitled to have it, as long as it goes away and does not keep happening once a monetary transaction has transpired. I must ask, have you donated? and does the pop-up still happen?

**Comment by flagrama** [comment]
If you did significant work on the emulator, sure, you could make an argument for it with Zilmar. Those of us who have contributed know we haven't contributed nearly as much as he has, so we make no argument for him to change it.

**Comment by LordEnma** [comment]
> > > Then put in the actual work for it. Depriving one of the developers of compensation for all the work they do in one of the emulators isn't going to help, it'll just make them stop working on it and it will die since there aren't other contributors doint the work they are doing. And even removing the timer will affect that because people will just skip the pop-up if there is no timer for it.
> > 
> > 
> > That is the sacrifice you make when you release software for free. Welcome to the internet
> 
> Ok now that isn't the attitude [LordEnma](https://github.com/LordEnma), If the Author wants a support window they are entitled to have it, as long as it goes away and does not keep happening once a monetary transaction has transpired. I must ask, have you donated? as does the pop-up still happen?

This software is open source, so it is subject to scrutiny by the community by default, and from what i hear, not many people like this. In the end, it is up to the head dev as to whether or not to have the window, but since it is open source, we are allowed to debate on it

**Comment by Squall-Leonhart** [comment]
Many of us have contributed for years in the form of testing, support, RDB changes, Cheat additions, Source contributes.

Our voices carry more weight then some rando with his first pull request that believes themselves the proprieter of what is and isn't the basis of open source.

The donation screen can stay.

**Comment by TheGent** [comment]
> > > > Then put in the actual work for it. Depriving one of the developers of compensation for all the work they do in one of the emulators isn't going to help, it'll just make them stop working on it and it will die since there aren't other contributors doint the work they are doing. And even removing the timer will affect that because people will just skip the pop-up if there is no timer for it.
> > > 
> > > 
> > > That is the sacrifice you make when you release software for free. Welcome to the internet
> > 
> > 
> > Ok now that isn't the attitude [LordEnma](https://github.com/LordEnma), If the Author wants a support window they are entitled to have it, as long as it goes away and does not keep happening once a monetary transaction has transpired. I must ask, have you donated? as does the pop-up still happen?
> 
> This software is open source, so it is subject to scrutiny by the community by default, and from what i hear, not many people like this. In the end, it is up to them as to whether or not to have the window, but since it is open source, we are allowed to debate on it

Ok but have you donated and does it go away? If it does, then you really have no argument to be honest.

**Comment by LordEnma** [comment]
> > > > > Then put in the actual work for it. Depriving one of the developers of compensation for all the work they do in one of the emulators isn't going to help, it'll just make them stop working on it and it will die since there aren't other contributors doint the work they are doing. And even removing the timer will affect that because people will just skip the pop-up if there is no timer for it.
> > > > 
> > > > 
> > > > That is the sacrifice you make when you release software for free. Welcome to the internet
> > > 
> > > 
> > > Ok now that isn't the attitude [LordEnma](https://github.com/LordEnma), If the Author wants a support window they are entitled to have it, as long as it goes away and does not keep happening once a monetary transaction has transpired. I must ask, have you donated? as does the pop-up still happen?
> > 
> > 
> > This software is open source, so it is subject to scrutiny by the community by default, and from what i hear, not many people like this. In the end, it is up to them as to whether or not to have the window, but since it is open source, we are allowed to debate on it
> 
> Ok but have you donated and does it go away? If it does, then you really have no argument to be honest.

I haven't donated. And im sure 99 percent of people using this software dont either

**Comment by flagrama** [comment]
Like I said, anyone who has a problem with it already has many other options. There's nothing to debate here though. Zilmar does the work, he has chosen how donations are requested. The only things it being open source means is you are free to contribute, fork, read, and use it. Or to choose not to.

**Comment by LordEnma** [comment]
> Many of us have contributed for years in the form of testing, support, RDB changes, Cheat additions, Source contributes.
> 
> Our voices carry more weight then some rando with his first pull request that believes themselves the proprieter of what is and isn't the basis of open source.
> 
> The donation screen can stay.

I think the wider community has the same resolve that I do, but yes, you are correct, you do have more of a voice that I do

**Comment by LordEnma** [comment]
> Like I said, anyone who has a problem with it already has many other options. There's nothing to debate here though. Zilmar does the work, he has chosen how donations are requested. The only things it being open source means is you are free to contribute, fork, read, and use it. Or to choose not to.

And im contributing, or at least giving my case for a change i would like to be made

**Comment by TheGent** [comment]
> Many of us have contributed for years in the form of testing, support, RDB changes, Cheat additions, Source contributes.
> 
> Our voices carry more weight then some rando with his first pull request that believes themselves the proprieter of what is and isn't the basis of open source.
> 
> The donation screen can stay.

heh, yes we have, but to be fair, along as support has been given and the screen no longer impedes performance, it is indeed fine.

**Comment by GodOf-Thunder** [comment]
All said and done. I choose to use other emulators that don't nag me for money every time I start it.

**Comment by flagrama** [comment]
Good for you.

**Comment by LordEnma** [comment]
I just dont think free software should lock features besides early development releases, including the ability to skip a wait time, behind a pay wall of any kind. But that is my and the at large communities opinion, what you guys think overrides this, in the end

**Comment by TheGent** [comment]
> I just dont think free software should lock anything besides early development releases, including the ability to skip a wait time, behind a pay wall of any kind. But that is my and the at large communities opinion, what you guys think overrides this, in the end

I personally feel you need to donate a little to test your standing now, if after doing so the software becomes better to use then it defeats your issues. If not you have fortified your ground imo. You can not complain that you are hard done by but are not willing to pay a little to justify an argument.

**Comment by flagrama** [comment]
You've already been told that you're free to make your own fork and maintain and distribute it as you like if you feel that strongly.

> I just dont think free software should lock anything besides early development releases, including the ability to skip a wait time, behind a pay wall of any kind.

Better tell Red Hat and many other open source projects they're not allowed to put support behind a paywall anymore. Of course that'll likely collapse the entire open source ecosystem outside of hobby projects like this.

**Comment by LordEnma** [comment]
Lmao I clearly meant features, you clearly don't wanna listen to the community, so i wont donate, but I will donate to emulators that actually listen to the community

**Comment by LordEnma** [comment]
> You've already been told that you're free to make your own fork and maintain and distribute it as you like if you feel that strongly.
> 
> > I just dont think free software should lock anything besides early development releases, including the ability to skip a wait time, behind a pay wall of any kind.
> 
> Better tell Red Hat and many other open source projects they're not allowed to put support behind a paywall anymore. Of course that'll likely collapse the entire open source ecosystem outside of hobby projects like this.

And you act like my opinion is the most important and impactful one? It clearly isnt?

**Comment by GodOf-Thunder** [comment]
> You've already been told that you're free to make your own fork and maintain and distribute it as you like if you feel that strongly.
> 
> > I just dont think free software should lock anything besides early development releases, including the ability to skip a wait time, behind a pay wall of any kind.
> 
> Better tell Red Hat and many other open source projects they're not allowed to put support behind a paywall anymore. Of course that'll likely collapse the entire open source ecosystem outside of hobby projects like this.

Since I would be using Red Hat in a non hobbyist environment, donating to it or paying for the right to use it with an expectation that I am protected from issues that would impact my livelihood. I find that your comment has any validity in the real world.

**Comment by LordEnma** [comment]
i'm just gonna wrap this up. Clearly the devs aren't interested in making their main product better or listening to feedback, even when emulators that dont have stupid wait times and are made by small teams or even just a single person still make thousands a month. But even with overwhelming community opinion against this, the devs just say "lol so go make ur own dumbass lmao", which isn't a very constructive thing to say to a user. Coupled with being rude and taking what i say out of context, I dont recommend making any constructive changes to this software. The devs will just reject any pull request that makes any changes to the support window, so there is no point in continuing.

**Comment by project64** [comment]
@LordEnma at the end of the day I am the only real dev on this project, as others have stated they contributed to the project, but I would guess over 95% is mine (outside of the gfx plugin).

if you want an argument for it staying, most free products have ads, google, youtube, facebook, etc .. so having an ad for my my self is not really that unsual. 

If you want to compare Project64 to yuzu .. it just is not. I did have a patreon and still do, but was lucky to crack $200 a month compared to $20,000 that yuzu does, so that is not really an option. 

If I could just use patreon get that type of level of support then, yes there would be no need of these feature, but this is not the world we live in, I can not run google ads as they do not support windows applications.

I have been working on this project for a long time and dedicated a lot to n64 emulation as has other developers. You can still use everything for free with just having an ad ad the start. The source is also completely open source so you can modify it your self if your really opposed to supporting it or use a different emulator. 

At the end of the day you saying I dislike this nag window, and it should not be there so should be removed so I get stuff for free and the developer should make money someway that does not effect me. Which is the arragancy that some other comments have responded to, and attacked instead of reasonsed.

**Pull request closed without merging**
