### PR TITLE
Fix Rat Attack entry in RDB

### PR DESCRIPTION
**Pull request by Frank-74**

### CODE REVIEW

**Comment by dsx-** [comment]
lol woops, why did i put 0, my bad

**Comment by project64** [comment]
> lol woops, why did i put 0, my bad

probably cause it is 0 in the cfg file and No in the rdb

**Comment by cxd4** [comment]
0's better

**Comment by project64** [comment]
yes, which is why it is in the cfg file .. but I kept backwards support to how the rdb worked originally.

**Comment by cxd4** [comment]
That then would be for the most part a good thing in that case.

**Pull request merged**
