### PR TITLE
Fix RE2 depth issues with Glide64

### PR DESCRIPTION
**Pull request by AmbientMalice**
This fixes https://github.com/project64/project64/issues/213

### CODE REVIEW

**Comment by cxd4** [comment]
http://ft.trillian.im/785abe041074fd64135ab3318aff1ec8767ab03d/6wOcP6Ysw5XjCWgHtRXessw9BQlOz.jpg

I don't think that fixed it.
I know the check box for software depth buffer rendering is checked this time after pulling from this commit, but it isn't fixed for me either.  If it is fixed for AmbientMalice then something external to the Glide64 configuration must be helping it.

**Comment by Frank-74** [comment]
I'm wondering if PJ_Glide64 is from the Glide64 final version.  As there are other issues that don't happen with Glide64 final.  The bond portrait in Goldeneye for example.  Displays correctly in Glide final, yet is split in 2 with a line down the middle in PJ_Glide.

**Comment by AmbientMalice** [comment]
@cxd4 @Frank-74 I can think think of a number of possible causes. They all revolve around Framebuffer Objects, and by association ATI/AMD GPUs.

FBOs are disabled by default in Glide64. Enabling them breaks RE2's depth. Traditionally, FBOs are associated with better performance on ATI hardware. I don't really know why.

Are either of you using AMD GPUs?

**Comment by Frank-74** [comment]
Yes, on board ATI Radeon Xpress.

**Comment by AmbientMalice** [comment]
Do you have "Use Frame Buffer Objects" disabled?

**Comment by Frank-74** [comment]
Yes FBO's are disabled.  With Software depth buffer rendering enabled and FBO's disabled, it works.  Its just very slow with software depth buffer.

**Comment by Lithium64** [comment]
@AmbientMalice HD 4650 1GB here with FBO disabled

**Comment by Frank-74** [comment]
You need to uncheck Hide Advanced Settings in pj64 options to see the Emulation Settings tab in Glide with the software depth buffer option.

Anyway, now I'm getting a 'GL_INVALID_OPERATION" , "Update Screen" message box, as soon as the spinning logo disappears, only when I have Software depth buffer enabled.  Using the Glide debug build.

**Comment by cxd4** [comment]
> Are either of you using AMD GPUs?

Nope I have a GeForce.

> Anyway, now I'm getting a 'GL_INVALID_OPERATION" , "Update Screen" message box, as soon as the spinning logo disappears, only when I have Software depth buffer enabled. Using the Glide debug build.

I put the OpenGL debugging only in UpdateScreen since that's the function that gets constantly called by Project64 all the time.  I think I should move the debugging to happen at the end of each of the Glitch64 GL command segments.

`GL_INVALID_OPERATION` means different things for different functions, so I might have to make the debugger more specific.  It can mean corrupt data in the vertex arrays, or it can happen with a complete loss of the GL context.

**Pull request merged**
