### PR TITLE
[core] compile errors from not declaring standard <string.h> functions

### PR DESCRIPTION
**Pull request by cxd4**

### CODE REVIEW

**Comment by project64** [comment]
I wonder if it is better to add the #include stdio and #include string to the stdafx

**Comment by cxd4** [comment]
Possibly.

The con to that is more intervention from the pre-processor...if `stdafx.h` includes `string.h` in every single .cpp file throughout the source, even when string.h isn't needed, then more things like unneeded macros get added every time.

But for `<stdio.h>` maybe stdafx.h is better because that header is larger and contains more things than string...string.h I don't imagine should slow down the compile time all that much just by including it.

**Comment by cxd4** [comment]
Maybe somebody with a slow computer can run some tests on how long it takes to compile Project64 with all the standard C header includes (stdlib, stdio, string, memory, math, float, limits ... http://www.tutorialspoint.com/c_standard_library/index.htm) moved out of the .cpp files and into afxres.h ?

**Comment by cxd4** [comment]
https://github.com/cxd4/project64/compare/2ebf64503a...bc1405b6af

**Pull request merged**
