### PR TITLE
fix Character corruption in Rom Browser

### PR DESCRIPTION
**Pull request by Nekokabu**
fix Character corruption in Rom Browser
https://github.com/project64/project64/issues/731

### CODE REVIEW

**Comment by Frank-74** [comment]
I'm getting build errors after applying this fix.  I get 3 failed after Rebuild All.
For example:
```
17>Main.cpp
17>c:\Users\Mary\Documents\25-11-15\project64-wx_3.0\Source\Common/std string.h(36) : error C2061: syntax error : identifier 'DWORD'
17>c:\Users\Mary\Documents\25-11-15\project64-wx_3.0\Source\Common/std string.h(38) : error C2061: syntax error : identifier 'DWORD'
17>.\Main.cpp(1097) : error C2668: 'stdstr::ToUTF16' : ambiguous call to overloaded function
17>        c:\Users\Mary\Documents\25-11-15\project64-wx_3.0\Source\Common/std string.h(38): could be 'std::wstring stdstr::ToUTF16(void)'
17>        c:\Users\Mary\Documents\25-11-15\project64-wx_3.0\Source\Common/std string.h(37): or       'std::wstring stdstr::ToUTF16(bool *)'
17>        while trying to match the argument list '(void)'
17>.\Main.cpp(1097) : error C2228: left of '.c_str' must have class/struct/union
```
But I'm using wx3.0, because it gets rid of the initiate problems when using Azimer's 0.7 and having Glide Final in the plugins directory.

**Comment by cxd4** [comment]
>error C2061: syntax error : identifier 'DWORD'

In this case it's supposed to be `uint32_t`, not `DWORD`, in the commit.

I have no comment on the C++ errors.

**Comment by Frank-74** [comment]
: fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory

**Comment by cxd4** [comment]
Heh.  Yeah one thing I like about VC2008:  It doesn't compile extensions like stdint.h. =]

You have to include zilmar's `<Common/systypes.h>` or something, whatever it was called.  That's where he works out all the stdint.h types for compilers that don't support stdint.h (and in my not-so-humble opinion, have no obligation to).

**Comment by Frank-74** [comment]
It's `<Common/stdtypes.h>`

**Comment by Nekokabu** [comment]
OK?

**Comment by Frank-74** [comment]
Seems to be ok, but why do I get these strange characters for (J) Internal Name?
internalerr1

**Comment by project64** [comment]
I made some changes (https://github.com/project64/project64/commit/5b7020453e184ccc2af04b5cd5b0d9b1d95aa894) so that the rom browser is using W char version instead of A version so this might change if this fix is needed any more .. tho it might cause other problems

**Comment by Frank-74** [comment]
@project64 Now all Internal Names are Chinese.

internalerr2

**Comment by cxd4** [comment]
lol.  I love it when that happens (to me, when I used to mess with ansi vs. unicode)

**Comment by project64** [comment]
@Frank-74  thanks add a fix (https://github.com/project64/project64/commit/2cc85dd2cfbdfd4bf6c5f8dbc941314a1c211608) should fix the internal names .. at least for ansi based ones

**Comment by Frank-74** [comment]
@project64 Ok, now its back to how it was before.

internalerr3

**Comment by project64** [comment]
@Frank-74 great, tho not sure about internal names for jap games, I am converting ascii to tuf16, maybe it should be a different code page or somthing

**Comment by Frank-74** [comment]
@project64 Maybe https://en.wikipedia.org/wiki/Code_page_932 ?

**Comment by Frank-74** [comment]
Erm...  Not sure how I managed it yet, but....

japnames

**Comment by Frank-74** [comment]
```cpp
wcscpy(pRomInfo->InternalName, stdstr(InternalName).ToUTF16(932).c_str());

**Pull request closed without merging**
