### PR TITLE
Fix "Unable to load state"

### PR DESCRIPTION
**Pull request by samuelyuan**
Before
before

After
after

To get this message,
Select a Save Slot that doesn't exist (such as Save Slot 10)
Click "Load State (F7)"
The message "Unable to Load State"  will appear along with the full path

### CODE REVIEW

**Comment by Frank-74** [comment]
How do I make this message appear?

**Comment by cxd4** [comment]
That always happens with some projects of mine, too.  I don't know why.

You can see it in plain view as well:
https://github.com/Frank-74/project64/blob/6007d9bce0144b45bc065422fb3886b75d97a92e/Source/Project64/N64%20System/N64%20Class.cpp#L1383

My guess is GitHub has a table of valid sprintf specifiers (like %s for string, %i for int, %X for hex ... then it saw %w[...anything at all] after your change and did not recognize the wide-string mode of a printf token as a valid usage of printf.

**Comment by Frank-74** [comment]
I copied the line into the load state to see it displayed, because I couldn't make it fail.
It shows the whole directory string before the state name.

This will make it say for example `Unable to load state Castlevania (U) (v1.2).pj.zip`
```cpp
	g_Notify->DisplayMessage(5, stdstr_f("%ws %s", GS(MSG_UNABLED_LOAD_STATE), CPath(FileNameStr).GetNameExtension().c_str()).ToUTF16().c_str());
```

**Comment by cxd4** [comment]
```c
printf("%a", x);
printf("%b", x);
printf("%c", x);
printf("%d", x);
printf("%e", x);
printf("%f", x);
printf("%g", x);
printf("%h", x);
printf("%i", x);
printf("%j", x);
printf("%k", x);
printf("%l", x);
printf("%m", x);
printf("%n", x);
printf("%o", x);
printf("%p", x);
printf("%q", x);
printf("%r", x);
printf("%s", x);
printf("%t", x);
printf("%u", x);
printf("%v", x);
printf("%w", x);
printf("%x", x);
printf("%y", x);
printf("%z", x);
```

**Comment by Frank-74** [comment]
```cpp
printf(L"ws", x);
```

**Comment by cxd4** [comment]
GitHub's coolness points just increased.

It only supports ANSI C89 printf specifiers, not that C99 horseshit.

**Comment by Frank-74** [comment]
@cxd4 Why then does samuelyuan's change not have a red %?

**Comment by samuelyuan** [comment]
Is the message supposed to show the entire path or just the name of the save state?

Also, I can't get Save State to work for some reason.

**Comment by cxd4** [comment]
um...dunno Frank..

Guess we'll find out if and when zilmar merges this.

For now samuelyuan's `%` is white, not red.  I guess after the PR is merged it turns red?

**Comment by Frank-74** [comment]
@samuelyuan 
Save State (F5) is working fine here.  Can you give more details, what game?

**Comment by samuelyuan** [comment]
I'm not sure which game. 

I get this error message:
error

**Comment by cxd4** [comment]
Did you "Enable Debugger" checkbox through the pj64 settings to see if that error adds any detail?

**Comment by Frank-74** [comment]
I only get that message when trying to Load State when a save state doesn't exist.

**Comment by samuelyuan** [comment]
<code>
Error  : Break point found at N64 System\Mips\Memory Virtual Mem.cpp 2014
</code>

**Comment by Frank-74** [comment]
Enable Debug messages as well in App logging.
I get this trying to load a save that doesn't exist.
```
: Debug  : CMainMenu::ProcessMessage: ID_SYSTEM_RESTORE
: Debug  : CN64System::LoadState(C:\Users\Frank\Documents\02-12-15\project64-master\Bin\Package\Save\CRUIS'N WORLD.pj): Start
: Error  : Unknown memory action

Emulation stopped
```
And its cleaner just showing the filename instead of the whole directory.  I cannot even see the filename, its cut off because of my long directory.

**Comment by Frank-74** [comment]
@samuelyuan 
Try changing the g_Notify message here : https://github.com/project64/project64/blob/master/Source/Project64/N64%20System/N64%20Class.cpp#L1339
From this:
```cpp
g_Notify->DisplayError(GS(MSG_FAIL_OPEN_SAVE));
```
To this:
```cpp
g_Notify->DisplayMessage(5, stdwstr_f(L"%ws", GS(MSG_FAIL_OPEN_SAVE)).c_str());
```
Do you still get Unknown memory action on Save State?

**Comment by samuelyuan** [comment]
There's still an error mainly because the program doesn't reach that point at all. I think the error happens when the program tries to write to a zip file in the lines above. 

I think this discussion should be moved to a separate issue, just in case anyone else experience a similar problem.

**Comment by Frank-74** [comment]
Yes, create a new issue for this.

In the meantime, try adding debug messages throughout the SaveState() section, add 1,2,3,4 etc for each one, so you know where the program got to by reading the Project64.log.

Example:
```cpp
 WriteTrace(TraceDebug, __FUNCTION__ ": 1");
 WriteTrace(TraceDebug, __FUNCTION__ ": 2");
```

**Comment by Frank-74** [comment]
Only just noticed your edit in the top post.
`To get this message,
Select a Save Slot that doesn't exist (such as Save Slot 10)
Click "Load State (F7)"
The message "Unable to Load State" will appear along with the full path`
Before this PR, I got Unknown memory action when doing this, not corrupted text.

**Comment by Frank-74** [comment]
@samuelyuan 
```
This line seems to be the problem.
https://github.com/project64/project64/blob/master/Source/Project64/N64%20System/N64%20Class.cpp#L1323
zipWriteInFileInZip(file, m_MMU_VM.Rdram(), RdramSize);
```

**Comment by samuelyuan** [comment]
It works after I unchecked 'Automatically compress saved states'. Thanks.

**Pull request merged**
