### PR TITLE
[Installer] Fix permissions - desktop icon option

### PR DESCRIPTION
**Pull request by Frank-74**
Fixes permissions for Windows 7/8/10.  And correct Program Files (x86) folder when running on 64bit windows.

### CODE REVIEW

**Comment by Frank-74** [comment]
I think Project64 needs to set the security/access permissions directly as well.  So that it can be unzipped to any folder and run.

Been reading up, and maybe need to implement this: https://msdn.microsoft.com/en-us/library/windows/desktop/aa379579(v=vs.85).aspx

**Comment by project64** [comment]
the Project64.exe would have to be run as an administrator for the Project64.exe to  change the permissions.. 

This really just applies if you are in the program files directory so for a zip package does not matter so much

**Comment by Frank-74** [comment]
Not on Windows 8+.  I just downloaded and extracted the v220 zip from the beta forum.  It doesn't run under any directory other than below Users directory.

Even changing permissions for the folder and running Project64.exe as an administrator, it gives an Exception caught in main.cpp, line 99.  Unless under the Users directory.

**Comment by project64** [comment]
if you run as administrator does it work correctly?

i suspect that at startup it should check if it running as admin, in which case change the permissions of the dir, if not then check what the permissions of the directories are and if they are not correct then do a prompt and exit.

**Comment by Frank-74** [comment]
I only have myself on this computer.  I login as an administrator.  I set project64.exe to run as administrator.  I change the folder permissions to full control.  Still doesn't run under any directory outside of Users.

**Comment by project64** [comment]
I mean right click and choose run as administrator

**Comment by Frank-74** [comment]
> I mean right click and choose run as administrator

Doesn't work...

**Comment by Frank-74** [comment]
Still one weird problem.

Project64.exe doesn't run if in "C:\Project64 2.3", but it does run if in, "C:\Project64 2.3\Project64 2.3"
With the zip and the installer.

It needs another directory layer for some strange reason.

Anything like C:\N64\Project64 2.3 or, C:\Games\Project64 2.3 etc. is fine.

**Comment by Frank-74** [comment]
Used to have 
https://github.com/project64/project64/blob/71cc6def7b35f0d533d2b8a108834823834ac288/Source/Project64/main.cpp#L40

**Comment by Frank-74** [comment]
I've found the bug that causes the exception in main.cpp if run from C:\Project64.

https://github.com/project64/project64/commit/b2545c108bf597e8d4d8455381f73c5e365d6c06#diff-49d517f4abbfa5c428ffaea9a380bbfcL454

I added this back and it's now working in C:\folder.

**Comment by project64** [comment]
ok commited, does the code now solve all the issue with permissions, or there is still some cases that need more work?

I am thinking of maybe doing a 2.3.1 with these changes.

**Comment by Frank-74** [comment]
Eveything solved as far as I've tested.

I've extracted the zip to C:\project64, and it works fine now.  I've tested it on a USB stick with no folder, H:\Project64.exe, works fine now.  I've run the installer, fine installed in Program Files, Users, C:\.

2.3.1 release is a good idea.  Surprised this bug went undetected since April.

**Comment by project64** [comment]
not really surprising, most likely cause people were using zip not the installer and if they were building it was up multiple levels.

maybe it could be done easily to add an "install as portable" which just basically would not add the registry options for uninstall.

**Comment by Frank-74** [comment]
There's an example in the inno setup help.

> [Setup]
Uninstallable=not IsTaskSelected('portablemode')
[Tasks]
Name: portablemode; Description: "Portable Mode"

**Comment by project64** [comment]
yes something exactly like that :)

**Comment by Frank-74** [comment]
Need to add IsTaskSelected to this line as well I think.

Name: "{commonprograms}\Project64 2.3\Uninstall Project64 2.3"; Filename: "{uninstallexe}"; Parameters: "/LOG"

I'll give it a go.

**Comment by Frank-74** [comment]
Ok, i've done it.  Virtually just cut and paste from inno help's Uninstallable option.
https://github.com/project64/project64/pull/1182

**Pull request merged**
