### PR TITLE
[Disk] Add Disk Drive Settings file

### PR DESCRIPTION
**Pull request by LuigiBlood**
Forgot to add those, sorry about that.

### CODE REVIEW

**Comment by project64** [comment]
you might have to re enable the code I disabled to get it to compile

**Comment by LuigiBlood** [comment]
I've done it in ddrevamp_fix but I'll compile it first on my end, then do the PR

**Comment by project64** [comment]
jni\Project64-core/N64System/N64DiskClass.h:129:40: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
    const uint16_t SCYL_ZONE_TBL[2][8] = {

**Comment by LuigiBlood** [comment]
Man I tried to do const to optimize things but I didn't think C++ sucked that much...

That said I do not have that warning on my end?

**Comment by LuigiBlood** [comment]
Should I add them to the constructor instead then? Or is there a better thing possible in C++? That really seems messy to me.

**Pull request merged**
