### PR TITLE
Update About.cpp

### PR DESCRIPTION
**Pull request by Alen-Alic**
(grammar fixes and more 'thanks' credits added in about window)

### CODE REVIEW

**Comment by CrashOveride95** [comment]
yes very useful, pj64 will never be the same

**Comment by Alen-Alic** [comment]
> yes very useful, pj64 will never be the same

Every little bit helps my sarcastic friend.

**Comment by CrashOveride95** [comment]
> > yes very useful, pj64 will never be the same
> 
> Every little bit helps my sarcastic friend.

Alright, so you think you can add yourself to the list of people who have made actual contributions to the codebase because you fixed *A grammatical error*
OK buddy

**Comment by CrashOveride95** [comment]
Also, you did the same thing almost a month ago #1870 but closed it shortly before making this new one with the exact same useless changes

Is this some new form of attention-seeking I am unaware of?

**Pull request closed without merging**
