### PR TITLE
Add Visual Studio 2013 support, remove non essential projects, bug fixes and re-implemtation

### PR DESCRIPTION
**Pull request by death-droid**
Add Visual Studio 2013 support, remove non essential projects that should be split into seperate repositories. bug fixes and re-implemtation

### CODE REVIEW

**Comment by project64** [comment]
way to many changes for the pull request, this needs to be broken down. I maybe able to go though your log and look at pulling each commit individually.

**Comment by death-droid** [comment]
>.< Git's pull system is to much of a pain in the ass to make changes since i tend to do work in bunches Its easy to end up with 6 commits lined up.

**Comment by project64** [comment]
https://blogs.law.harvard.edu/acts/2012/07/10/github-pull-request-for-just-one-commit/

**Comment by death-droid** [comment]
Cheers for that mate!

**Pull request closed without merging**
