### PR TITLE
Update Audio.rdb

### PR DESCRIPTION
**Pull request by Frank-74**
Added settings I found, only (U) versions added for now.

### CODE REVIEW

**Comment by theboy181** [comment]
every single (U) game? What about games that will be written in the future?

Only Joking. 

I'm still puzzled as to why N64 audio emulation needs per game settings. How do other emulators get audio right?

Another question I have about per game settings is what if a games FPS/DL's change does affect the audio, does it also change the needs for the audio settings? Are some games using dynamic audio solution to increase performance?

**Comment by MelchiorGaspar** [comment]
maybe audio or some other advanced timings are coded in the ROM some where??
probably the only way... the N64 would know... but idk...

**Comment by LegendOfDragoon** [comment]
> How do other emulators get audio right?

pro-tip, they don't :smile: 

>Are some games using dynamic audio solution to increase performance?

Some games do change fps in certain parts, but idk if it's for performance reasons or what.

**Comment by loganmc10** [comment]
> pro-tip, they don't 😄

That's not really true. Try https://m64p.github.io (download the latest version and try it out, I implemented a better resampler this week, so whatever bit of crackling might have existed before should be gone). It gets the audio right 99% of the time. I think Hey You! Pikachu is the only game I know of that has terrible audio with mupen64plus. There are no per-game audio settings. There aren't even per-game VIRefresh settings anymore.

I think relying on massive RDB files with specific settings for each game is the wrong way to go. It's no secret that mupen64plus has benefited by implementing fixes from Project64. I think Project64 could benefit from looking at audio emulation in mupen64plus.

**Comment by theboy181** [comment]
@loganmc10 is your calculation of 99% based on actual math,or an expression. I see a load of developers who make claims based on thought. 

Anyway, I am glad to hear that you have improved audio. Any improvement in N64 audio is a step in the right direction. 

To me audio has always been a bunch of unknown, and people who don't claim to be experts of it. Brings me back to why does the N64 audio scene lack good audio emulation.

**Comment by loganmc10** [comment]
> @loganmc10 is your calculation of 99% based on actual math,or an expression. I see a load of developers who make claims based on thought.

Well I provided the link so you can try for yourself. I would call it an expression of actual math ;)

**Comment by oddMLan** [comment]
Yeah, the RDB shouldn't even be necessary except for general purpose speedups I guess, like 32-bit mode and such.

Audio shouldn't have hardcoded values to run properly, a general-purpose solution should exist, that should estimate the correct values on-the-fly, without needing user interaction or a database with hard coded values to read from. There is a huge amount of N64 games and software, setting this on a per game basis would be insane. Wouldn't mind as much if it was just a few oddball games that needed fine-tuning.

**Comment by oddMLan** [comment]
Also, don't know why you dislike FAT so much, it's a general purpose solution that works fantastically for me and fixes audio pops and such for the games I play (dunno about Clay Fighter, Goldeneye... games I don't usually open).

A general purpose solution that works 90% of the time (and its heuristics could always get improved) it's better than having hardcoded values. What if the timing in the emulator becomes more accurate, and these values no longer work? Maintenance burden.

**Comment by Frank-74** [comment]
@loganmc10 I've tried it out.  Tested 3 games.  Body Harvest, crackles and video stutters, video/audio go way out of time with each other.  Goldeneye video stutters badly, crackles like hell because of it, then froze with black screen during after intro, just before level demo starts.  DK64, crackles, video stutters badly.
Recordings:
https://www.dropbox.com/s/tdvwu9l2zn0vqit/m64p_goldeneye.mp3?dl=0
https://www.dropbox.com/s/52bb9z11tfrd56l/m64p_bodyharvest.mp3?dl=0
https://www.dropbox.com/s/p6v2n7ilbv3tzrc/m64p_dk64.mp3?dl=0

@oddMLan Try my last build of Project64-Audio with built in settings for a number of games, list is in zip.  It also has a number of fixes not commited to git yet.  Turn FAT off.  DK64 needs Counter Factor set to 2 for correct timing.
https://www.dropbox.com/s/s4di6nqwxj8m132/Project64-Audio-Frank74.zip?dl=1

**Comment by loganmc10** [comment]
> @loganmc10 I've tried it out. Tested 3 games. Body Harvest, crackles and video stutters, video/audio go way out of time with each other. Goldeneye video stutters badly, crackles like hell because of it, then froze with black screen during after intro, just before level demo starts. DK64, crackles, video stutters badly.

Obviously there is a lot more going on there than the audio. Does GLideN64 work for you in Project64? Somehow you and @LegendOfDragoon are the only people that can't seem to get it working properly...

Anyway doesn't matter, whether you two can figure out how to work your computers or not, what I'm talking about is the audio emulation code in mupen64plus, which does work well with on a decent computer/user combo. There seems to be more interest in tweaking RDB files than improving emulation over here, so I would say go ahead and merge it!

**Comment by LegendOfDragoon** [comment]
>@loganmc10 is your calculation of 99% based on actual math,or an expression. I see a load of developers who make claims based on thought.

When people use estimates in the 90 percentile range, I've learned not to trust the claim :smile: . I would never claim something like that, until I actually tested enough to factually back the claim.

>It gets the audio right 99% of the time.

I wish it did, but it doesn't even come close on my end. I got crackling in a few games like WDC, Gauntlet, etc. Then I had stuttering in other games like Top Gear Rally and Deadly Arts (not sure if audio, gfx, or core is to blame though).

>There is a huge amount of N64 games and software, setting this on a per game basis would be insane.

I'd rather spend 2 minutes tweaking settings for each game, than to have to deal with crackling or stuttering. Ideally it would be nice to not have to do that, but there is no current better option.

**Comment by Frank-74** [comment]
Project64 with my Project64-Audio, FAT off, latest WIP3 GLideN64 default settings.
There's one interruption in the audio when I got a message notification from Discord.
https://www.dropbox.com/s/xlwp48ispscqaz7/pj64-audio_dk64.mp3?dl=0
Goldeneye and Body Harvest are perfect too.

**Comment by LegendOfDragoon** [comment]
>Somehow you and @LegendOfDragoon are the only people that can't seem to get it working properly...

What? GLideN64 works on my machine.

>what I'm talking about is the audio emulation code in mupen64plus, which does work well with on a decent computer/user combo.

So basically you're just going to assume it's somehow the user's fault?

>There seems to be more interest in tweaking RDB files than improving emulation over here

How is it "improving emulation", if it still sounds worse than other emulators?

**Comment by oddMLan** [comment]
@Frank-74, if that's the case, I'm looking forward to the new timing method.

@loganmc10  I find that odd too. Probably because they are using laptop hardware with a crappy Intel IGP. Never really had an issue with the current audio timing personally, except for a couple of oddballs.

Really not a big fan of per-game hacks personally. One should work from what's accurate and then focus how to make it faster, not work with something already not accurate enough and focus on making it even more innacurate because it doesn't run good enough with your hardware. How about asynchronous audio? There would be no stutter.

At that point, why not writing a custom emulator/wrapper customized for every game?

Enhancements are a different story though, Widescreen and 60FPS are enhancements that are optional. Wonder if there's a way to make the jumbotron refresh at a higher rate with a cheat code instead of a plugin hack.

**Comment by LegendOfDragoon** [comment]
>Probably because they are using laptop hardware with a crappy Intel IGP. 

My laptop only supports OGL 2.1, so I can't even test on that if I wanted to. So that's not the reason.

>One should work from what's accurate

Nothing is accurate for audio.

>At that point, why not writing a custom emulator/wrapper customized for every game?

That would actually be great, but would require much more time than tweaking audio settings.

>Really not a big fan of per-game hacks personally. One should work from what's accurate and then focus how to make it faster

Neither am I, but I will take a better experience over a worse experience any day.  A few mins spent tweaking, is much better than hearing crackling on a regular basis.

**Comment by oddMLan** [comment]
I get what you mean, of course non-crackling audio > crackling audio, but at what cost? It feels like an incentive to keep hacking around things instead of actually solving them. Which might even break later on with other changes to the audio plugin or internal emulator timing.
Imagine if someone thought that Glide64 was already good enough with all its hacks and tried to hack the rest of the games to "improve" it (instead of reversing the uCodes and improving framebuffer emulation for a general purpose). Would GLideN64 be a thing now? Improving things on a surface level might be enough to fool end users but, what if you can't find the time to keep maintaining the project, and someone complained a particular game was broken at a certain point, which you have never played? Would you jump in and work around it? Tweaking the settings would work for you in particular, but doubt the end-user would try to tweak the values manually if the defaults didn't work good enough for them. So this kind of approach would make Project64 more of a simulator rather than an emulator.

**Comment by oddMLan** [comment]
I guess I can compromise with these values but only if they are meant as temporary, but still I am not sure... gonetz has implemented hacks in GLideN64 and then replaced them with a general purpose solution later on.

Also they would need more testing, since these are hardcoded, these might not work at all points where the games change FPS. Or under a different hardware configuration. Can't test right now, no access to my computer till the next couple weeks.

**Comment by LegendOfDragoon** [comment]
I have to say, this plugin seems to work pretty good for Smash Bros on my so-called "toaster" laptop :smile: . I'm not even using these RDB setings yet (doesn't seem necessary for SSB). Looks like Project 64's audio has good potential.

>Would you jump in and work around it?

I go out of my way to help end users :smile: . Even if I didn't have the time to personally tweak it for them, i could tell them what to tweak. Essentially, i can teach end users how to fish.

Tbh i'm not sure if all of Frank's changes are necessary. I have found that per-game settings are not necessary for your average game (with the right setup). Only reason I'd tweak a lot of games is to enhance my experience (minimizing latency and adjusting for possible issues like performance). For instance, I have to raise latency when using Angrylion's plugin for some games (Mario kart comes to mind).

>Which might even break later on with other changes to the audio plugin or internal emulator timing.

That's more of a problem for FAT. With FAT disabled, that's less likely to be an issue.

>It feels like an incentive to keep hacking around things instead of actually solving them. 

Literally nobody in this scene knows how the N64's audio truly works. People have tried their best, in order to come up with the current results. Getting audio to work right, is far more challenging than getting graphics to work. For graphics, you can refer to documentation and you're set for the most part. Audio doesn't have much documentation.

**Comment by Frank-74** [comment]
> I have to say, this plugin seems to work pretty good for Smash Bros on my so-called "toaster" laptop :smile: . I'm not even using these RDB setings yet (doesn't seem necessary for SSB).

It needs buffer change for the plugin audiosync to keep around 60 with frame limiter off.  Without buffer changes, it goes above 60 which is potentially a crackle with frame limiter on.

**Comment by theboy181** [comment]
@frank I’m not by a computer now, but when I tested last all the games would run faster or slower than 60vi with some of the settings. Has that been addressed?  Can you unlock the frame lint with this plugin?

**Comment by Frank-74** [comment]
@theboy181 yes, audiosync is off by default in main branch at the moment.
You can turn it on/off with configure audio > game settings, and check/uncheck audiosync.
I'm just adding some of my improvements to a branch I just created at my fork.

**Comment by Frank-74** [comment]
Done, you can view my changes here: https://github.com/project64/project64/compare/master...Frank-74:Project64-Audio-improvements
Test build here: https://www.dropbox.com/s/airfp9vy23w8sf4/Project64-Audio.zip?dl=1

**Pull request merged**
