### PR TITLE
Formatting fixes on RDB

### PR DESCRIPTION
**Pull request by Lithium64**
All settings were organized in alphabetical order 
**(Please respect the alphabetical order when editing the RDB It is annoying having to correcting this every time)**
Removed duplicated blank lines
Reverted Sync Audio to 0 - No need to change it because it works fine
Removed ViRefresh=1500 on RDB since it's default value
Removed AiCountPerBytes=400 on RDB since it's default value
Removed CustomSMM from RDB this setting isn't used in the current version of PJ64

**The settings below are working fine and should be Default when editing RDB**

RDB Option            Default Value|Other Value(s)

// Config:
RDRAM Size          = 4|8
Save Type           = First Save Type|4kbit Eeprom|16kbit Eeprom|FlashRam|Sram
Counter Factor      = 2|1|3|4|5|6
ViRefresh           = 1500|?
AiCountPerBytes     = 400|?
32bit               = Yes|No
Use TLB             = Yes|No
Delay DP            = Yes|No
Delay SI            = No|Yes
Fixed Audio         = 0|1
Sync Audio          = 1|0
Audio Signal        = No|Yes
ScreenHertz         = 60|50

// Recompiler
Cpu Type            = Recompiler|Interpreter|SyncCores
FuncFind            = 1|2           // 1=Physical 2=Virtual
Reg Cache           = Yes|No
Linking             = On|Off
Fast SP             = Yes|No

// Self Mod Methods
SMM-Cache           = 1|0
SMM-PI DMA          = 1|0
SMM-TLB             = 1|0
SMM-FUNC            = 1|0
SMM-Protect         = 0|1
SMM-StoreInstr      = 0|1

// Plugins
HLE Audio               = 0|1
HLE GFX                 = 1|0
Culling                 = 0|1
Direct3D8-Direct3DPipe  = 0|1
Direct3D8-DesiredAspect = 0|1
Direct3D8-2xSai         = 0|1
Direct3D8-ForceFilter   = 0|1
Direct3D8-Brightness    = 0|0-30
Dsound-SyncAudio        = 0|1

// Other
Rom In Memory           = 0|1
TLB: PAddr Start        = 0|?
TLB: Vaddr Len          = 0|?
TLB: Vaddr Start        = 0|?

### CODE REVIEW

**Comment by Frank-74** [comment]
I made that list for 2.1.  Some default values have changed for 2.2.  VIRefresh=1500, AiCountPerBytes=400 and Fixed Audio Timing=0

**Comment by Lithium64** [comment]
@Frank-74 Thanks, I will fix this.

**Comment by Frank-74** [comment]
I left out Emulate Clear and Clear Frame plugin options, because they don't change the settings in Jabo's plugin.  Probably CustomSMM option can be removed as well, as there is no such option in 2.0+.

**Comment by Lithium64** [comment]
@Frank-74 I plan to remove CustomSMM I was expecting to talk to Zilmar for know if really this setting has no use anymore, if Emulate Clear and Clear Frame has no use would be good remove them too

**Comment by Frank-74** [comment]
It would be good if the Clear Frame option could be made to work from the RDB though.  None of the options for the ROM settings tab in Jabo's, can be saved or set from the RDB.

**Comment by MELERIX** [comment]
if you can, please add documentation comments inside the file, also with info about the default values, in order to avoid future people adding lines with default.

**Comment by AmbientMalice** [comment]
I'll do my best to keep any rdb changes alphabetical in future.

**Comment by dsx-** [comment]
all ViRefresh=1500 should be removed since 1500 is the default

**Comment by Lithium64** [comment]
@dsx- Removed, thanks for reminding me.

**Comment by cxd4** [comment]
I would have kept them in in case 1500 actually was the near-perfect value for them...just because 1500 the default value doesn't mean the default value can't change in a future build.

**Comment by MELERIX** [comment]
> just because 1500 the default value doesn't mean the default value can't change in a future build.

in that case the documentation about defaults values should be updated, no sense to add default values for each rom.

**Comment by cxd4** [comment]
I have no idea what you said, but, there is no documentation on "default values", at least for this setting.

It's been changed time and time already, from 1500 to 2200 and eventually back to 1500.  There's no such thing as "duplicated default values"; if a game NEEDS 1500 VI refresh rate, then you should set it to 1500 in the RDB.  Who cares what the core default is..if the game needs it; document it.  That's what the RDB is for.

**Comment by MELERIX** [comment]
thats why I've requested above if he can add the documentation inside the file.

my quote
> if you can, please add documentation comments inside the file, also with info about the default values, in order to avoid future people adding lines with default values.

**Comment by project64** [comment]
I did also have a program to sort the rdb, does that help?

**Comment by Lithium64** [comment]
@MELERIX I think it's better to create a separate file for this

**Comment by MELERIX** [comment]
btw, there is some more values that require documentation about its defaults values, for example:

CustomSMM=?/?
Emulate Clear=?/?
Primary Frame Buffer=?/?
Self Texture=?/?

**Comment by Lithium64** [comment]
@dsx- I've removed AiCountPerBytes=400 on RDB also since it's default value

**Pull request merged**
