### PR TITLE
Terminate rest of source with line breaks to neaten Git parsing.

### PR DESCRIPTION
**Pull request by cxd4**
Git parsing seems to like to complain when a programming source code file isn't newline-terminated.  Kept noticing it in a few of the pull requests done on here.

Something about 95% of Project64 source already seems to follow that ancient tradition of specifying a line return at the end of the code file, but I guess a few random files / their counterparts forgot to keep consistent with that trivial thing.

An example:  `$project64/Source/Project64/Plugins/GFX plugin.h`.  This header has no newline at the EOF, but the headers for some other plugin types and `RSP plugin.cpp` do.

didn't feel like desecrating Smiff's/Gent's 1.6/1.7 documentation TXT files, just the Git C source pretty much, and the German language file...those support files could end up getting replaced/redone by someone anyway

Wouldn't exactly offend me if this pull request was declined.  I'm not even familiar with the traditional reasoning behind this religious little nitpick; I just felt like completing the EOF newline-termination for the other 5% of Project64 source because GitHub and Git version compare console explicitly wrote about missing newlines when you go to view/compare the files.

### CODE REVIEW

**Comment by project64** [comment]
ok, should hopefully be merged

**Comment by cxd4** [comment]
>ok, should hopefully be merged

@project64 : I am not seeing any changes in today's commits regarding this.  I think it's fine to decline a pull request for changes this trivial, but on the other hand, you say that it should be merged now, when only one of your commits has inserted any newlines, and only in a couple maybe 3 files I think, when this pull request fixed it for tens of files.  Wouldn't it have just been easier to merge my commit using GitHub, or refuse it, rather than to partially replicate the change over a couple files?

**Comment by project64** [comment]
I did not close it cause it was trivial.

I tried again I could not auto merge because of other changes, when ever I try to merge it here so I can comit the changes because git on my machine discards the changes. So I merged here and pushed, i did not see it discarded the changes because it thought they were the same.

**Comment by project64** [comment]
you might need to create a new pull request with the changes

**Comment by cxd4** [comment]
Okay.

Never minding that for now.  Yeah I'll re-send the PR later on, but first working on a few Glide warning fixes.

**Comment by cxd4** [comment]
I was supposed to have the pull request for Glide64 warning fixes done tonight, but it looks like this line-break termination PR here really screwed me over big time.  It looks like you had a problem with merging it because death accidentally committed a newline at the end of a couple files.  I thought by force-pushing and force-overwriting the existing branch I could have bypassed that but I guess not.

I'll start over when I wake up tomorrow.  In the meantime @project64 if it helps at all you can look at the changes I pushed before failing to execute the pull request here:  https://github.com/cxd4/project64/compare/15e389cbe2...d92465deaa

**Pull request closed without merging**
