### PR TITLE
RDB overhaul part 5 - organize the RDB into much smarter categories, general cleanup

### PR DESCRIPTION
**Pull request by DerekTurtleRoe**
Make new sections, update a few entries, remove some inaccurate information, and fix some typos and other issues.

### Proposed changes
Make sections for:
- N64 games ✅
- N64DD games ✅
- Aleck64 games ✅
- iQue games ✅
- Fan translations ✅
- Prototypes ✅
- ROM hacks ✅
- ROMs extracted from other releases/ports ✅
- Randomizers ✅
- NTSC to PAL conversions, NTSC-J to PAL conversions, and PAL to NTSC conversions ✅

- Clean up and fix a dozen entries or so

Please merge PR 4 before this, it is required 👍 

In a future PR, I may try to convert all "good name" and "internal name" entries into a single No-Intro name convention entry with info from N64DB as well, but that will be a much more involved change, so not in this PR. 😄 

### Does this make breaking changes?
No.

### Does this version of Project64 compile and run without issue?
Yes.

### CODE REVIEW

**Comment by IlDucci** [comment]
Someone will be waiting here when the PR is merged to add some non-English translations... Good luck with the reorganization.

**Comment by DerekTurtleRoe** [comment]
> Someone will be waiting here when the PR is merged to add some non-English translations... Good luck with the reorganization.

Are you referring to yourself? I will most likely have to axe these PRs and make a new PR because of how I did them, so it'd be helpful to know ahead of time.

**Comment by IlDucci** [comment]
> Are you referring to yourself? I will most likely have to axe these PRs and make a new PR because of how I did them, so it'd be helpful to know ahead of time.

Yes, sorry, I was referring to myself. So yeah, I wanted to help adding non-English translations, but if you're going to start from scratch, I can no longer use this thread as a way to know when to help.

**Comment by DerekTurtleRoe** [comment]
> > Are you referring to yourself? I will most likely have to axe these PRs and make a new PR because of how I did them, so it'd be helpful to know ahead of time.
> 
> Yes, sorry, I was referring to myself. So yeah, I wanted to help adding non-English translations, but if you're going to start from scratch, I can no longer use this thread as a way to know when to help.

I am basically going to just isolate some of the changes and make them individual commits and remove some things Zilmar doesn't want changed, so it should be similar enough you can still contribute after the commits are done. I will keep you informed, hopefully some time soon I can take a look at this again, I've been sick and had some real life stuff going on lately, but this weekend I wanna tackle some projects.

**Comment by DerekTurtleRoe** [comment]
Going to close this and make a new PR

**Pull request closed without merging**
