### PR TITLE
Updates encoding of Lang/French.pj.Lang

### PR DESCRIPTION
**Pull request by Watilin**
Addresses #172 

I double-checked all accented chars in the file, but couldn't compile to see if anything's been broken -- can't install Visual Studio at the moment. It *normally* shoudn't break, but if someone is willing to test the french version.

**Note:** in Github website, the file will appear as containing diamonds with question marks. This is normal: the site interprets contents as UTF-8 while the file is actually ANSI.

Also, I'm willing to fix spelling mistakes and improve typography, but I'm not sure I could put this in the same PR, as this seems to me like something completely different from an encoding issue.

I'll wait for your comments ;)

### CODE REVIEW

**Comment by project64** [comment]
the file can not be ansi it has to be utf-8 file

**Comment by Watilin** [comment]
Ok, this also answers the question I was asking to myself about why the project wasn't using UTF-8 for all langs :P
Actually the issue I was adressing relates to Jabo's plugin, so this PR is pointless. I'm closing it.

**Comment by Watilin** [comment]
Just one dumb question, and I'm sorry if it's already been asked: all translation files begin with a byte order mark. Is this on purpose? I've been told that BOM is only necessary when carrying a stream over network.

**Comment by project64** [comment]
yes the BOM is necessary with out it the file is treated and ansi file instead of utf8 file. Project64 will also now not load any language file that does not have the BOM

**Comment by cxd4** [comment]
It also is necessary for The Duck Song.  https://www.youtube.com/watch?v=MtN1YnoL46Q

**Comment by Watilin** [comment]
Nooo it's that song again, I thought I could forget it  >_<

**Pull request closed without merging**
