### PR TITLE
Super Mario 64 wobble fix

### PR DESCRIPTION
**Pull request by AmbientMalice**
This should fix the wobbling on ground textures in Mario 64. Fix comes from libretro. Not aware of any regressions.

### CODE REVIEW

**Comment by cxd4** [comment]
Interesting.

Basically all that change suggests is magnifying the (x, y, z) coordinates by (w *= 100), so 100% each coord. instead of 1% each coord.

**Comment by LegendOfDragoon** [comment]
How come it keeps including merges from other PR's?

**Comment by AmbientMalice** [comment]
>How come it keeps including merges from other PR's?

Because I can't *git gud* and keep my repo up to date by making PRs from the main repo.

**Comment by cxd4** [comment]
Keeping repo up-to-date should be done always from the master branch, not topic branches.

The master branch should be kept clean except for git pull's and fetch's to sync with upstream merges before checking out each new branch for each new PR.

**Comment by Lithium64** [comment]
@AmbientMalice Do you know how change the default plugin on retroarch?

**Comment by vgturtle127** [comment]
@Lithium64 If you can, I can't figure it out. RetroArch isn't the easiest emulator to configure sometimes...

**Comment by GPDP2** [comment]
Start a game. Press F1 to go to the menu. Press Z until you're all the way back to the main menu, then select Quick Menu, then Core Options. You'll see the option for GFX Plugin. Press left and right to choose between plugins. Angrylion requires the CXD4 RSP plugin to work. Once you choose a plugin, restart RetroArch so the change will take effect.

Alternatively, open the retroarch-core-options.cfg file (should be in the /retroarch/configs directory) and edit the mupen64-gfxplugin and mupen64-rspplugin entries manually before starting the program. The relevant options for gfxplugin are gln64, rice, glide64, and angrylion, while the ones for rspplugin are hle and cxd4.

For more information, see this link:

http://emulation.gametechwiki.com/index.php/Using_RetroArch#Mupen64Plus

**Comment by Lithium64** [comment]
@GPDP2 Thanks, i was trying to figure out it for a long time.

**Comment by vgturtle127** [comment]
@GPDP2 Yeah, me too! Thanks!

Although, it doesn't fix any of the problems with the Mupen64Plus core. :laughing:

**Comment by LegendOfDragoon** [comment]
@AmbientMalice you should get your main branch in sync with project64. I have no trouble just doing git pull, then sync, for anytime i want to update to latest commit. Since you are 1 commit ahead, you will need to fix that first. I cannot remember how I fixed that problem on my end.

**Comment by oddMLan** [comment]
git force push to latest commit from the upstream master repo

**Pull request merged**
