### PR TITLE
64DD support overhaul

### PR DESCRIPTION
**Pull request by LuigiBlood**
Currently overhauling 64DD support almost entirely.

### Features:
- 64DD Disk Images now appear in the ROM Browser, Recent Games as well.
- Seperate settings for each 64DD disk (RDB and User Config)
- Refactored game loading into core instead of UI.
- Unload Disk and 64DD IPL when playing a regular N64 game (frees memory when you don't need it, reminder that a 64DD Disk is almost 64MB)
  - This also fixes that exception error when it's about to save a disk file when it was not used.
- Forge Header of a 64DD game for plugin usage (or not? a discussion could be done about that)
  - Done but I'm not sure if I caused a bug with GUI Messages now or before then...
- More explicit error messages.
- Handle 64DD IPL loading errors better.
- **RDB to contain 64DD game configurations**
- Translation in French

### TODO:
- Proper Rom Information window for 64DD games?
- ***FIX BUGS***

### CODE REVIEW

**Comment by LuigiBlood** [comment]
To be honest I think the real meat of this overhaul is done, it's all polish at this point (still don't merge yet).
So that's nice :)

**Comment by LuigiBlood** [comment]
image
No one should complain about the lack of notification anymore :)

**Comment by LuigiBlood** [comment]
While I think this could be merged now, maybe some people might want to test it first, I also have to update the RDB as well for future work.

**Comment by LuigiBlood** [comment]
image
This is good enough for me now.

**Comment by oddMLan** [comment]
Super Mario 64 (Disk version) is missing in the Rdb. Other than that, excellent work! 😄

**Comment by LuigiBlood** [comment]
I somehow forgot that. But then that means I have to do actual CRC because Mario 64 Disk does not have any Disk ID in it.

**Comment by oddMLan** [comment]
imagen

.ndd roms aren't reading the "Fixed Audio=0" setting from their RDB entry.

imagen
The IPL rom reads it successfully however. Which makes me think something is wrong with the .ndd setting handling.

Also, if you right click a N64DD game from the ROM browser, then try to edit its settings, 1 out of 3 times it crashes the emulator.

**Comment by LuigiBlood** [comment]
I thought there was an issue with something else, actually, but I guess not.

**Comment by oddMLan** [comment]
Well it's not 1 out of 3 times after all. More like 1 out of 5 times. To reproduce the 'Edit Settings' crash more easily, close the emulator every time afterwards. Then open again, select game -> Edit settings. If it did not crash close and repeat, eventually it does crash.

>You sure you didn't disable Fixed Audio Timing in Defaults? Because honestly it does not read it when I do it on 64DD IPL either.

I didn't.

**Comment by LuigiBlood** [comment]
Okay I get what you mean: I had already found this bug but I'm really not sure where the cause is, it's a hard to debug thing.

**Comment by oddMLan** [comment]
imagen
SM64Disk showing these warnings, but otherwise game loads fine.

**Comment by Frank-74** [comment]
Fixed Audio setting is read from Audio.rdb.  I've changed it to be read from Project64.rdb in this branch.
https://github.com/Frank-74/project64/tree/FAT-SUA-defaults

**Comment by LuigiBlood** [comment]
...Okay I know why Mario 64 Disk is doing this I think: It has no Game ID or anything whatsoever. So it's a mess there. I think that's the plugin that's confused.

**Comment by Frank-74** [comment]
Ok, I've done a small PR that moves Fixed Audio setting back to Project64.rdb.
https://github.com/project64/project64/pull/1580

**Pull request merged**
