### PR TITLE
Upgrade wxWidgets to version 3.0.2

### PR DESCRIPTION
**Pull request by JunielKatarn**
Two main reasons for this change:
1. Version 2.8 is rather old, and the wxWidgets forums have mentions of many improvements in newer versions (since 2.9).
2. Some dependencies used by the 2.8 codebase made it impossible to build Project64 with a non MSVC toolset with xp compatibility (e.g. vs14_xp would work, but vs14 would fail). This change fixes this, allowing compilation in other compilers such as LLVM 3.8 and Intel Compiler Collection (verified myself). This will help the transition to other compilers easier.

Tested:
* Built all flavors (Win32, x64, Debug, Release) and combinations.
* Tested the Glide64 plugin configuration GUI (which uses wxWidgets) successfully.
* Ran Ocarina of Time, World Cup 98 and Lem's crap test ROM without issues.

### CODE REVIEW

**Comment by tony971** [comment]
Working fine for me. Admittedly, I only built the win32 release.

**Comment by Frank-74** [comment]
Tried building complete solution.  Doesn't build with VS2008.  Lots of errors.

```
1>.\src\msw\gdiimage.cpp(489) : error C2039: 'ExtractIconEx' : is not a member of '`global namespace''
1>.\src\msw\gdiimage.cpp(489) : error C3861: 'ExtractIconEx': identifier not found
1>.\src\msw\gdiimage.cpp(502) : error C2039: 'ExtractIconEx' : is not a member of '`global namespace''
1>.\src\msw\gdiimage.cpp(502) : error C3861: 'ExtractIconEx': identifier not found
1>.\src\msw\gdiimage.cpp(515) : error C2039: 'ExtractIcon' : is not a member of '`global namespace''
1>.\src\msw\gdiimage.cpp(515) : error C3861: 'ExtractIcon': identifier not found

1>c1xx : fatal error C1083: Cannot open source file: '.\src\msw\gsockmsw.cpp': No such file or directory

1>c1xx : fatal error C1083: Cannot open source file: '.\src\msw\slider95.cpp': No such file or directory

1>c1xx : fatal error C1083: Cannot open source file: '.\src\msw\statbr95.cpp': No such file or directory

1>c1xx : fatal error C1083: Cannot open source file: '.\src\msw\tbar95.cpp': No such file or directory

1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(23) : error C2146: syntax error : missing ';' before identifier 'poleobj'
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(23) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(23) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(24) : error C2146: syntax error : missing ';' before identifier 'pstg'
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(24) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(24) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(25) : error C2146: syntax error : missing ';' before identifier 'polesite'
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(25) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(25) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(86) : error C2065: 'IRichEditOle' : undeclared identifier
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(86) : error C2065: 'IUnknown' : undeclared identifier
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(87) : error C2448: 'DECLARE_INTERFACE_' : function-style initializer appears to be a function definition
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(116) : error C2143: syntax error : missing ';' before '*'
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(116) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(116) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(128) : error C2065: 'IRichEditOleCallback' : undeclared identifier
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(128) : error C2065: 'IUnknown' : undeclared identifier
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(129) : error C2448: 'DECLARE_INTERFACE_' : function-style initializer appears to be a function definition
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(156) : error C2143: syntax error : missing ';' before '*'
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(156) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\richole.h(156) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>.\src\msw\textctrl.cpp(169) : error C2516: 'IRichEditOleCallback' : is not a legal base class

1>c1xx : fatal error C1083: Cannot open source file: '.\src\generic\panelg.cpp': No such file or directory

1>Build log was saved at "file://C:\Users\Frank\Documents\22-11-15\project64-master\build\Release\core\BuildLog.htm"
1>core - 33 error(s), 1 warning(s)

15>c1xx : fatal error C1083: Cannot open source file: '.\src\common\datacmn.cpp': No such file or directory

15>.\src\common\filename.cpp(1386) : error C2065: 'SHFILEOPSTRUCT' : undeclared identifier
15>.\src\common\filename.cpp(1386) : error C2146: syntax error : missing ';' before identifier 'fileop'
15>.\src\common\filename.cpp(1386) : error C2065: 'fileop' : undeclared identifier
15>.\src\common\filename.cpp(1387) : error C2065: 'fileop' : undeclared identifier
15>.\src\common\filename.cpp(1387) : error C2065: 'fileop' : undeclared identifier
15>.\src\common\filename.cpp(1387) : error C2070: ''unknown-type'': illegal sizeof operand
15>.\src\common\filename.cpp(1388) : error C2065: 'fileop' : undeclared identifier
15>.\src\common\filename.cpp(1388) : error C2228: left of '.wFunc' must have class/struct/union
15>        type is ''unknown-type''
15>.\src\common\filename.cpp(1388) : error C2065: 'FO_DELETE' : undeclared identifier
15>.\src\common\filename.cpp(1389) : error C2065: 'fileop' : undeclared identifier
15>.\src\common\filename.cpp(1389) : error C2228: left of '.pFrom' must have class/struct/union
15>        type is ''unknown-type''
15>.\src\common\filename.cpp(1390) : error C2065: 'fileop' : undeclared identifier
15>.\src\common\filename.cpp(1390) : error C2228: left of '.fFlags' must have class/struct/union
15>        type is ''unknown-type''
15>.\src\common\filename.cpp(1390) : error C2065: 'FOF_SILENT' : undeclared identifier
15>.\src\common\filename.cpp(1390) : error C2065: 'FOF_NOCONFIRMATION' : undeclared identifier
15>.\src\common\filename.cpp(1393) : error C2065: 'fileop' : undeclared identifier
15>.\src\common\filename.cpp(1393) : error C2228: left of '.fFlags' must have class/struct/union
15>        type is ''unknown-type''
15>.\src\common\filename.cpp(1393) : error C2065: 'FOF_NOERRORUI' : undeclared identifier
15>.\src\common\filename.cpp(1396) : error C2065: 'fileop' : undeclared identifier
15>.\src\common\filename.cpp(1396) : error C3861: 'SHFileOperation': identifier not found

15>c1xx : fatal error C1083: Cannot open source file: '.\src\common\wxchar.cpp': No such file or directory

15>Build log was saved at "file://C:\Users\Frank\Documents\22-11-15\project64-master\build\Release\base\BuildLog.htm"
15>base - 22 error(s), 0 warning(s)

16>LINK : fatal error LNK1181: cannot open input file '..\..\bin\release\lib\wxbase28.lib'
16>Build log was saved at "file://C:\Users\Mary\Documents\22-11-15\project64-master\build\Release\Glide64\BuildLog.htm"
16>Glide64 - 1 error(s), 2 warning(s)

17>LINK : fatal error LNK1181: cannot open input file '..\..\plugin\gfx\lib\pj64glide64.lib'
17>Build log was saved at "file://C:\Users\Frank\Documents\22-11-15\project64-master\build\Release\Project64\BuildLog.htm"
17>Project64 - 1 error(s), 3 warning(s)

========== Build: 13 succeeded, 4 failed, 1 up-to-date, 1 skipped ==========
```

**Comment by JunielKatarn** [comment]
Chang es erre made on the VCXPROJ makefiles. VS2008 files would also need to be upgraded.

In short, you just need to make the included headers and source files match the ones in the VCXPROJ equivalents.

**Comment by Frank-74** [comment]
I don't have time to work out what needs adding and how/where they need to be added, and in what files.  I'll just have to wait for it to be done by someone who knows how to do it.

**Comment by JunielKatarn** [comment]
You can also upgrade to Visual Studio 2015, Community Edition and forget about VS2008.

**Comment by cxd4** [comment]
>Chang es erre made on the VCXPROJ makefiles. VS2008 files would also need to be upgraded.

You need to look more closely at the errors Frank74 reported.  They have nothing to do with "cannot find X.h"; they're conflicts that cause compilation to fail, here, on Visual Studio 2013 Community as well.

tony971 last I heard uses VS2015 as well.

**Comment by cxd4** [comment]
```
error C2011: 'sockaddr' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\ws2def.h	212	1	base
error C2059: syntax error : 'constant'	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\ws2def.h	390	1	base
error C3805: 'constant': unexpected token, expected either '}' or a ','	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\ws2def.h	390	1	base
error C2011: 'sockaddr_in' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\ws2def.h	583	1	base
error C2011: 'fd_set' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	132	1	base
error C2011: 'timeval' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	176	1	base
error C2011: 'hostent' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	232	1	base
error C2011: 'netent' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	245	1	base
error C2011: 'servent' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	252	1	base
error C2011: 'protoent' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	264	1	base
error C2011: 'WSAData' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	360	1	base
error C2011: 'sockproto' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	458	1	base
error C2011: 'linger' : 'struct' type redefinition	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	500	1	base
error C2375: 'accept' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1578	1	base
error C2375: 'bind' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1600	1	base
error C2375: 'closesocket' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1619	1	base
error C2375: 'connect' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1638	1	base
error C2375: 'ioctlsocket' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1659	1	base
error C2375: 'getpeername' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1680	1	base
error C2375: 'getsockname' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1701	1	base
error C2375: 'getsockopt' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1724	1	base
error C2375: 'htonl' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1745	1	base
error C2375: 'htons' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1762	1	base
error C2375: 'inet_addr' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1780	1	base
error C2375: 'inet_ntoa' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1797	1	base
error C2375: 'listen' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1815	1	base
error C2375: 'ntohl' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1833	1	base
error C2375: 'ntohs' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1850	1	base
error C2375: 'recv' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1870	1	base
error C2375: 'recvfrom' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1895	1	base
error C2375: 'select' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1921	1	base
error C2375: 'send' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1945	1	base
error C2375: 'sendto' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1970	1	base
error C2375: 'setsockopt' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	1996	1	base
error C2375: 'shutdown' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2018	1	base
error C2375: 'socket' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2039	1	base
error C2375: 'gethostbyaddr' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2063	1	base
error C2375: 'gethostbyname' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2083	1	base
error C2375: 'gethostname' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2101	1	base
error C2375: 'getservbyport' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2121	1	base
error C2375: 'getservbyname' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2141	1	base
error C2375: 'getprotobynumber' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2160	1	base
error C2375: 'getprotobyname' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2178	1	base
error C2375: 'WSAStartup' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2200	1	base
error C2375: 'WSACleanup' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2219	1	base
error C2375: 'WSASetLastError' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2236	1	base
error C2375: 'WSAGetLastError' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2253	1	base
error C2375: 'WSAIsBlocking' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2270	1	base
error C2375: 'WSAUnhookBlockingHook' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2287	1	base
error C2375: 'WSASetBlockingHook' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2304	1	base
error C2375: 'WSACancelBlockingCall' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2321	1	base
error C2375: 'WSAAsyncGetServByName' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2343	1	base
error C2375: 'WSAAsyncGetServByPort' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2370	1	base
error C2375: 'WSAAsyncGetProtoByName' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2396	1	base
error C2375: 'WSAAsyncGetProtoByNumber' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2421	1	base
error C2375: 'WSAAsyncGetHostByName' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2446	1	base
error C2375: 'WSAAsyncGetHostByAddr' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2473	1	base
error C2375: 'WSACancelAsyncRequest' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2496	1	base
error C2375: 'WSAAsyncSelect' : redefinition; different linkage	C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include\Winsock2.h	2517	1	base
error C2079: 'wsa' uses undefined struct 'WSAData'	$project64\Source\3rd Party\wx\src\msw\utils.cpp	184	1	base
error C2664: 'int (WORD,WSADATA *)' : cannot convert argument 2 from 'int *' to 'WSADATA *'	$project64\Source\3rd Party\wx\src\msw\utils.cpp	185	1	base
error C2027: use of undefined type 'hostent'	$project64\Source\3rd Party\wx\src\msw\utils.cpp	211	1	base
error C2227: left of '->h_addr_list' must point to class/struct/union/generic type	$project64\Source\3rd Party\wx\src\msw\utils.cpp	211	1	base
error C2027: use of undefined type 'hostent'	$project64\Source\3rd Party\wx\src\msw\utils.cpp	218	1	base
error C2227: left of '->h_name' must point to class/struct/union/generic type	$project64\Source\3rd Party\wx\src\msw\utils.cpp	218	1	base
error C2259: 'FrameSite' : cannot instantiate abstract class	$project64\Source\3rd Party\wx\src\msw\ole\activex.cpp	934	1	core
```

**Comment by Frank-74** [comment]
Everything except Glide has built now since zilmar's commit.  https://github.com/project64/project64/commit/fa60e55f57134f689f6038882f811191f17d9bc7
```
========== Build: 16 succeeded, 1 failed, 1 up-to-date, 1 skipped ==========
```
Glide has too many errors to list here.
```
16>C:\Users\Frank\Documents\22-11-15\project64-master\Plugin/GFX/PJ64Glide64.dll : fatal error LNK1120: 297 unresolved externals
16>Build log was saved at "file://C:\Users\Mary\Documents\22-11-15\project64-master\build\Release\Glide64\BuildLog.htm"
16>Glide64 - 1704 error(s), 2 warning(s)
```

**Comment by cxd4** [comment]
Yes.  My VC2013 error list was based on after zilmar's fix commit, so the problem is far from over.

**Pull request merged**
