### PR TITLE
Removed more default values from Project64.rdb

### PR DESCRIPTION
**Pull request by MELERIX**
Clear Frame=0/1/2
Self Texture=0/1
Primary Frame Buffer=0/1
Emulate Clear=0/1
Culling=0/1

Based in Documentation from:
http://en.helpdoc-online.com/project64_1.6/source/html/4%20configuration/plugin_video_d3d6_romsettings.htm
&
http://www.pj64-emu.com/manual-and-guides/configuration%3a-jabo-direct3d8/rom-settings-tab-d3d8-v1.6/#zAnswerList_307

### CODE REVIEW

**Comment by Lithium64** [comment]
I thought there is no documentation about these settings

**Comment by cxd4** [comment]
Most of that is stuff from Jabo D3D6 1.5.2 plugin which I think is no longer included.  So I guess removing them from the RDB as long as the internal defaults within the plugin match them isn't exactly destructive.

**Comment by MELERIX** [comment]
yes, just that I can't find info/documentation about plugin version 1.7, so no idea which values still are used.

@project64 have you info about plugin version 1.7 and which values still are used ?

**Comment by cxd4** [comment]
only one of those that's still used is _Clear Frame_

**Comment by Frank-74** [comment]
Clear Frame setting in RDB doesn't change the setting in the plugin.  And changing the setting in the plugin doesn't write it to the .cfg either.  Only on 1.6 plugins it works with the rdb in the emulator folder.

Culling works with all Jabo's from 1.5 to 1.7.  Even though the option is only selectable in 1.5.2.  Especially noticeable in games like Perfect Dark or GoldenEye.  Switch off culling and the frame rate will drop a lot.

**Comment by MELERIX** [comment]
seems the plugin is not loading the values from the RDB, even if you change manually "Clear Frame" to 2 in RDB, the plugin still shows "Default" and even if you make changes in "Rom Settings" none of the options is saved.

so now I'm wondering if the plugin is broken ? or is something in Project64 causing the bug ?

**Comment by Lithium64** [comment]
@Frank-74 @MELERIX for these settings working is needed leave a empty rdb on pj64 root folder

**Comment by MELERIX** [comment]
tested and nothing... only Direct3D8-Direct3DPipe is saved but in Project64.cfg

**Comment by Frank-74** [comment]
These are the only Jabo RDB options I could get working.
>// Jabo Options
>Direct3D8-Direct3DPipe	=0
>Direct3D8-DesiredAspect=0|1|2|3	// Default|Stretch|Force 4:3|Force 16:9
>Direct3D8-2xSai=0
>Direct3D8-ForceFilter=0
>Direct3D8-Brightness= 0|0-30
>Dsound-SyncAudio=0
>Culling=0

**Comment by cxd4** [comment]
I know clear frame worked, at least in 1.6, as it was needed for several games to display right in Jabo's 1.6 plugin.  But maybe after 1.7 zilmar finally removed it so that is why you can't get it to work.

**Pull request merged**
