### PR TITLE
NRage GBCart, use actual address ranges rather than hacky method. No rea...

### PR DESCRIPTION
**Pull request by death-droid**
...l benefit to the hacky method as the code isnt that much cleaner and creates edge cases.

### CODE REVIEW

**Comment by project64** [comment]
there are a lot of changes there, are they just all cosmetic code clean up, or is there any change of functionality in the code?

**Comment by death-droid** [comment]
Change of functionality. original code used to grab highest three bits I think. This code instead makes sure the address ita using is with the range the cart actually uses.
Ive seen reports of people having problems with the original code, this should ensure it is at least working like the carts do

**Comment by death-droid** [comment]
Checked against https://github.com/djhworld/gomeboycolor/blob/master/src/cartridge/MBC5.go and subsequent code files to ensure their the right address ranges as well

**Comment by cxd4** [comment]
So it's GBC information on how to handle GB carts in the transfer pak...

Anyway to have this tested in practical use of the plugin to confirm that these changes improve/fix anything with transfer pak emulation?  Just to make firm sure about the code in use.

**Pull request merged**
