### PR TITLE
Few Missing Expansion Pak Games

### PR DESCRIPTION
**Pull request by MELERIX**
- Castlevania (U) (V1.1)
- Command & Conquer (E) (M2)
- John Romero's Daikatana (E) (M3)
- John Romero's Daikatana (U)
- Ken Griffey Jr.'s Slugfest (U)
- Madden NFL 2000 (U)
- Madden NFL 2001 (U)
- Madden NFL 2002 (U)
- Resident Evil 2 (E) (M2)
- Resident Evil 2 (U) (V1.0)
- Resident Evil 2 (U) (V1.1)
- Roadsters Trophy (U) (M3)
- South Park (E) (M3)
- South Park (U)
- Tony Hawk's Pro Skater 2 (E)
- Top Gear Hyper Bike (E)
- Top Gear Hyper Bike (U)
- Top Gear Rally 2 (U)
- Xena Warrior Princess - Talisman of Fate (U)

### CODE REVIEW

**Comment by Lithium64** [comment]
Resident Eviil 2 with 8MB will cause resolution bugs on glide64
https://github.com/project64/project64/pull/245

**Comment by MELERIX** [comment]
@Lithium64 uhm, what can we do then ? no way to fix it only for Glide64 ?

**Comment by MELERIX** [comment]
@Lithium64 uhm, what can we do then ? no way to fix it only for Glide64 ?

**Comment by MELERIX** [comment]
@AmbientMalice yes, I noticed, just wondering if we can make a fix only for Glide64, because it seems to cause issue in Glide64 only, maybe is a Glide64 bug ?

any idea ?

**Comment by AmbientMalice** [comment]
Glide64 is the only usable HLE plugin for the game as far as I am aware. If games can have plugin-specific hacks, they can probably have plugin-specific settings like expansion pak, but I'm not sure since I've never looked at that feature.

**Comment by MELERIX** [comment]
ok, here we go: https://github.com/project64/project64/pull/282 also added documentation about the reason.

**Pull request merged**
