### PR TITLE
Grammatical fixes to Project64 language class (English).

### PR DESCRIPTION
**Pull request by cxd4**
The past couple of pull requests about the English language file got me into trying it, though there were too many realizations to not have all the commits at once in a related PR.  I guess later I'll go to do the English language file, which I did not do in this pull request.  (I only touched `$project64/Project64/Multilanguage Source/Language Class.cpp`.)

### CODE REVIEW

**Comment by cxd4** [comment]
on an unrelated note
```
[2015.03.25 23:33:07] <DrCat> hey zilmar i forgot to ask, was there any special reason you had jumped from VC 6.0 all the way to VS 2008?
[2015.03.25 23:33:20] <DrCat> something you didn't like about VS 2002 to 2005 or it was just an unintended outcome
[2015.03.25 23:34:12] <theboyBNC> off topic.. Was wondering if there was any cahnce that 64DD would be added for the release in April ?
[2015.03.25 23:34:19] <AIO> noo way ^
[2015.03.25 23:34:22] <DrCat> haha
[2015.03.25 23:34:23] *** zilmar (7346dde2@gateway/web/freenode/ip.115.70.221.226) has quit IRC: Ping timeout: 246 seconds
```

**Comment by cxd4** [comment]
There, pretty sure I've gotten everything now.

**Comment by MELERIX** [comment]
uhm...

PJ64 terminologies...

imho the first letters should be always upper case, because you can use "ABL" or "Advance Block Linking", but not "Abl" and not "Advance block linking", because that doesn't look good.

**Comment by cxd4** [comment]
No, because "advanced block linking" is not a store brand, newspaper article, advertisement, product, whatever.  It is a common noun.

"BTW" and "LOL" are also acronyms; however, you do not say "By The Way" or "Laugh Out Loud" just because the acronym version upper-cased those letters.

"ABL" is also not an official acronym.  It's another little made-up thing for quick chats.

**Pull request merged**
