### PR TITLE
Added missing roms

### PR DESCRIPTION
**Pull request by Lithium64**
I never edit a RDB before, please forgive my mistakes

There was a problem with formatting or enconding, don't know how to prevent this from happening, but I hope this helps anyway.

### CODE REVIEW

**Comment by project64** [comment]
ok, thanks for the pull request I will see about merging your changes in the morning

**Comment by project64** [comment]
https://github.com/project64/project64/commit/82b83199e002e047696dd4a8428a4a020387e377

I changed the file so it is utf-8 with the header, so hopefully it will not have this issue in the future.

**Comment by project64** [comment]
does this https://github.com/project64/project64/commit/c8a6bba702573fdad160a9596dcbba5a989924fb commit have all the missing roms now ?

**Comment by AmbientMalice** [comment]
The RDB is still missing Indiana Jones PAL, Superman 64 proto, Perfect Dark NTSC debug, Glover prototype, Animal Forest 90% English translation, and the Wonder Project J2 english translation. Plus a few others.

**Comment by Lithium64** [comment]
@project64 Yes, all roms who were on pull request were added

**Comment by cxd4** [comment]
> Superman 64 proto,

Come on.  Seriously? :D
I think we can do without even the **non-**proto version of that sorry POS.  Should be marked as "bad ROM".

**Pull request closed without merging**
