### PR TITLE
[RDB] Winback Grey Square Cheat Fix

### PR DESCRIPTION
**Pull request by Frank-74**
Fixed by @retrobenny
http://forum.pj64-emu.com/showpost.php?p=66179&postcount=6

### CODE REVIEW

**Comment by Frank-74** [comment]
Don't merge this yet, I haven't tested past the first level.  It might need a change.

**Comment by AmbientMalice** [comment]
They grey square issue is an HLE bug related to scrolling skies and scrolling water. So I imagine there will likely be some side effects.

**Comment by Frank-74** [comment]
Good point, retroben fixed the scrolling sky, they work with this fix, if the water is also broken, maybe that can be fixed too.

**Comment by Frank-74** [comment]
Closing because of complications with different regions.  Will redo it when it's all sorted.

**Pull request closed without merging**
