### PR TITLE
Add Visual Studio 2017 support.

### PR DESCRIPTION
**Pull request by JunielKatarn**
Non-intrusive changes.

### CODE REVIEW

**Comment by JunielKatarn** [comment]
Hey @project64, anything wrong with these changes?

**Comment by project64** [comment]
nothing is wrong with it, but I can not see how it actually changes anything

**Comment by JunielKatarn** [comment]
It git-ignores the .vs metadata folder (created starting VS2017).

It allows per-project formatting conventions (starting VS2017), which is useful for people working on different projects with different conventions.

Merely a developer convenience change.

**Comment by project64** [comment]
I think in part it was also been using spaces instead of tabs as well...

ok just do the .ignore file and I will merge

**Comment by JunielKatarn** [comment]
Reopened as #1299.

**Pull request closed without merging**
