### PR TITLE
Remove outdated language files that no longer work and add 4 new languages

### PR DESCRIPTION
**Pull request by DerekTurtleRoe**
Remove some old and unmaintained language files and add 4 new languages. This is in an effort to support the most popular languages, and also make it so more people can use Project64. 😄 

### Proposed changes
  - Remove old/unmaintained language files
  - Add 4 new languages (Bengali, Indonesian, Punjabi, and Vietnamese)

### Does this make breaking changes?
No.

### Does this version of Project64 compile and run without issue?
Yes.

If anybody who speaks those languages natively wouldn't mind, I'd appreciate it if you would look at the new language files and give feedback! 😄

### CODE REVIEW

**Comment by DerekTurtleRoe** [comment]
For some reason I'm having trouble with some of these getting detected, converting to draft in the meantime

**Comment by project64** [comment]
does the files have the ut8 bom in them, with out that project64 ignores it

**Comment by Squall-Leonhart** [comment]
they don't, neither do the 2 removed files.

**Comment by DerekTurtleRoe** [comment]
@project64 This is ready for review now! 😄

**Pull request merged**
