### PR TITLE
[+] Restore Project 64 1.7 functionality of being able to change plugins...

### PR DESCRIPTION
**Pull request by death-droid**
... while the emulator is running.

### CODE REVIEW

**Comment by death-droid** [comment]
@project64  just this commit needs looking over now

**Comment by project64** [comment]
Ok I been trying to get this working .. I committed some changes (https://github.com/project64/project64/commit/c973db8e350bb97797c5ed1d1d5727f22ffc14ca) to try and get it working.

It is not working and I am not sure why, I can switch to glide plugin fine, switching to jabo's plugin causes a crash, so I must be missing something.

**Comment by death-droid** [comment]
Hmmm seems to work for the most spart, switching from jabo to Rice and back to jabo seems to work for me. 
Glide is being weird for me, just complains about not knowing ucode or some shiz

**Comment by death-droid** [comment]
Also seems to bring in a few bugs that didn't occur / I had fixed in my own implementation. Will try and find some time tomorrow to see why its happening with your code, thats if you dont beat me to fixing it :P

**Comment by project64** [comment]
does this commit: https://github.com/project64/project64/commit/e05a7db66dbf62092b4c4e48002ed751c72d4a79 fix being able to switch?

**Comment by death-droid** [comment]
Did a quick test and cant seem to find any problems with it! Has my tick of approval.

**Pull request closed without merging**
