### PR TITLE
Allow for pushing two C Buttons at once when using an analog stick

### PR DESCRIPTION
**Pull request by Jeremy517**
These values specify how far an analog stick has to be pressed to count as a C Button press when C Buttons are mapped to an analog stick.  The old values did not allow for pressing two C buttons at once, because diagonals did not meet the values.  These values specifies that an analog stick must be pressed roughly halfway to count as a C Button press, which allows you to push two C Buttons at once.

### CODE REVIEW

**Comment by AmbientMalice** [comment]
Very good.This'll help with games that use the c-buttons for movement.

**Comment by Jeremy517** [comment]
These #defines aren't used for anything else.  Are there any concerns that are keeping this from getting merged?

**Comment by vgturtle127** [comment]
@Jeremy517 I don't believe so, why? Are you thinking about changing something?

**Comment by Jeremy517** [comment]
No, I was just curious as to why it hasn't been merged.

**Comment by vgturtle127** [comment]
@Jeremy517 I don't think @project64 knows about/has seen it yet. :wink:

**Comment by vgturtle127** [comment]
@Jeremy517 See. :wink:

**Pull request merged**
