### PR TITLE
Removed Adware

### PR DESCRIPTION
**Pull request by MELERIX**
no-ads

### CODE REVIEW

**Comment by AmbientMalice** [comment]
*Opens massive bag of dried corn, and pours it into a roaster*

This is gonna be awkward. @_@

I for one support the removal of the adware on the grounds that the prompts are obtuse and some of the offered adware strays too far into malware territory.

**Comment by MELERIX** [comment]
popcorn

jaja xD, well... someone had to do it, there is a lot of people complaining about the ads included in the installer, and these ads are not necessary for an Open Source project.

imho a button to donations in the website would be a better option instead of ads in the installer.

**Comment by cxd4** [comment]
The installer sucks anyway, with or without ads.  Zips and such are easier.

Also, zips and such suck anyway.  `git pull` && building from source FTW.

**Comment by vgturtle127** [comment]
I honestly never use installers for any of my emulators. I have an emulation directory (C:\Emulators\), and I store all my emulators and ROMS and everything there. The only emulators that give me trouble are Project64 and some other obscure emulators. Most of them have installers.

Here is a solution that I think would benefit both sides. Keep the installer, but also have a zip/7z version that people can download that is portable.

I know why they put ads in the installer, it's because they put a lot of effort into this emulator and it takes time and effort to build something like this. I think a link for donations would make more people willing to give money a better chance to do so, as oppose to forcing them to see an ad to give a much smaller amount of money.

Just a thought. Feel free to modify my ideas to better suit everybody. :smile:

**Comment by utterbull** [comment]
I'd just like to throw my 2 cents in.

Including known malware in an installer is absolutely disgusting and completely unacceptable. It needs to be removed immediately.

**Comment by vgturtle127** [comment]
"Known malware"

I don't see any malware in the installer when I run it. What are you referring to?

**Comment by MELERIX** [comment]
I guess this...

Baidu-International: Adware.Win32.Somoto.Q
ESET-NOD32: Win32/Somoto.Q potentially unwanted
McAfee: Artemis!0E858FBA5D93
TrendMicro-HouseCall: Suspicious_GEN.F47V0402

https://www.virustotal.com/file/ab522f7eff1092b0815b6b3b90d8efd09af12dab26219e67858075a496c23aa2/analysis/1428637981/

**Comment by AmbientMalice** [comment]
The installer makes a request of a third party server. Semi-random software is offered. Some of this software is a potential security risk. Some of it hijacks your web browser and can prove difficult to remove. (Not to mention the security risk associated with browser hijackers in general.)

**Comment by utterbull** [comment]
@vgturtle127 If you look at the code removed in the pull request you can see the malware in question is BetterInstaller.

**Comment by AmbientMalice** [comment]
@utterbull Better Installer isn't malware, per se. PJ64 itself comes with no "malware" inside it. The programs that *can* be offered via it, however, can be malware.

**Comment by vgturtle127** [comment]
It seems to me just to be advertisements and software that has been repackaged.

Don't get me wrong, I'm not condoning it, I had license violations on some of my software and I hated it, and I hate installers that have this sort of stuff in it. I just don't see anything malicious. :confused: 

It is up to the user whether or not to install such things anyway, and that is the reason I have Unchecky installed. :smile: 

And I think the general consensus is that people shouldn't install software offered to them during the install of other software. Hopefully anybody running a Nintendo 64 emulator has at least that much knowledge, and they must, because getting N64 games to run in any emulator with any plugins is fairly difficult. :laughing:

**Comment by AmbientMalice** [comment]
>It is up to the user whether or not to install such things anyway

Unwitting users end up installing dodgy software because this installer's prompts can be confusing.

**Comment by JunielKatarn** [comment]
+1
While pursuing revenue to support this free project's authors and their work, I believe embedding adware or any component that would install more software than the one the user expects (meaning, the emulator) is desirable.

Ads and "special offers" could be presented on the site's download page, but not in the final product (binaries).

**Comment by vgturtle127** [comment]
@AmbientMalice I know, but I'm guessing most of us aren't those kind of users. I'm assuming that due to the fact that N64 emulators are far beyond install and run. It doesn't matter really, if we remove it it would benefit everybody except the developers I suppose. But if they put a donation link I would definitely do it.

@JunielKatarn Everybody says that, but people don't necessarily know what goes on behind the scenes. Some people, like nocash for example, really need money to survive. And the little money they make from a popular emulator makes them enough money to keep them fed and ensure they have electricity and stuff. Again, I'm not condoning it, I'm just saying try to look at it from the point of view of others before you decide. I would like to hear from @project64 and @cxd4 and other project members about what they think. A donation model (like Stella) may be a really good idea.

**Comment by LegendOfDragoon** [comment]
>I would like to hear from @project64 and @cxd4 and other project members about what they think. A donation model (like Stella) may be a really good idea.

Well I'm fine with the ads staying, tbh. The reason why is because zilmar worked hard and has contributed a lot to the scene. So he deserves to earn a little cash. As for setting up a donation system, he has done that in the past. So I think he has his reasons for not currently doing that. zilmar knows what he is doing.

>Again, I'm not condoning it, I'm just saying try to look at it from the point of view of others before you decide.

I appreciate your consideration.

**Comment by MELERIX** [comment]
I was waiting an answer from zilmar, due he already removed ads previously, as you can see here: https://github.com/project64/project64/commit/a201d219eab294e70b2f17699de238d54efa962a

so I just did the same, but now with binno ads.

**Comment by MELERIX** [comment]
ok, is enough, 14 days waiting and seems there is no interest on removing the ads, so I'm closing this pull request.

sadly seems the people love the ads :S

**Comment by cxd4** [comment]
I am not at all interested in keeping the ads, but I am not interested in changing anyone else's mind on the matter either.  Money always gives me a headache when I think about software development--just like to think about the code, not the financials.  You guys are all welcome to think whatever you want though because I really don't know what to think about these other practical matters.

**Comment by MELERIX** [comment]
let's reopen this.

reasons:

http://forum.pj64-emu.com/showthread.php?t=4973
http://forum.pj64-emu.com/showthread.php?t=5084
http://forum.pj64-emu.com/showthread.php?t=5108

**Comment by Rukario** [comment]
Let's do it! Project 64 will be better by far without it.

**Comment by vgturtle127** [comment]
Does @project64 know if you can ask for certain ads not to be shown?

I really like being able to support Zilmar since his work in N64 emulation is priceless and much appreciated. I'm sure he has bills to pay and possibly a family to feed, so I consider it the least I can do to see some ads before I install his awesome emulator. :smile:

**Comment by utterbull** [comment]
I'd just like to throw my 2 cents in (again).

Including known malware (or ethically-ambiguous-ware that is known to install malware) in an installer is absolutely disgusting and completely unacceptable. It needs to be removed immediately. Lack of financial resources is never, ever, an excuse to harm the end-users.

**Comment by vgturtle127** [comment]
@utterbull I agree, but I wish we could just tell the ad company which ads were malicious, that way we could still use the ads to support @project64 but not get the malicious ads.

**Comment by cxd4** [comment]
Gentlemen, gentlemen.  Let's not get carried away.
I have the perfect solution to all of these malware/spyware/installerware concerns.
1.  Uninstall Windows.
2.  install Gentoo

**Comment by utterbull** [comment]
@cxd4 I think asking the user to change their OS just for a single program seems a bit extreme.

This really should not be a complex nor controversial issue. The malware needs to go.

**Comment by cxd4** [comment]
Never said it was for a single program.

With software everything on Windows is a complex and controversial issue. :)

**Comment by JunielKatarn** [comment]
Yeah, let's not stray from the topic. If you are a UNIX fanboy, there's not much to do on this discussion.
Project64 is a Windows application, so I suggest leaving the Microsoft-hating agenda out of this forums.

Now, back to the topic. I'd like to reiterate my earlier suggestion.
What about putting the ads in the download page?
They can be safely ignored (or clicked, if the user desires), and would leave the final product unadultered.

Anyway, this is zilmar's call.

**Comment by utterbull** [comment]
@JunielKatarn 
Forgive me for being blunt, but Zilmar doesn't have the guts to post in this thread. He's just going to sit it out because if he does, then nothing changes, and he can keep making money from the malware.

**Comment by cxd4** [comment]
```asm
	lea     rdi, .LC6[rip]
	call    puts@PLT
	lea     rdi, .LC7[rip]
	call    glXGetProcAddress@PLT
	mov     rdx, QWORD PTR glVertexAttribPointer@GOTPCREL[rip]
	lea     rdi, .LC8[rip]
	mov     QWORD PTR [rdx], rax
	call    puts@PLT
```
crashes but
```asm
	lea     rdi, .LC6[rip]
	call    puts@PLT
	lea     rdi, .LC7[rip]
	call    glXGetProcAddress@PLT
	lea     rdi, .LC8[rip]
	call    puts@PLT
```
doesn't.  I'm having a dilemma.  Why is 32-bit loading the Linux GL extension fine but not 64-bit?

**Comment by vgturtle127** [comment]
The bottom line is that @project64 is a person. This is his project and if he wants to anything with it, he can and has the right to. The project is open-source, so if you want to compile a version and call it the "no installer edition" or whatever you are more than welcome to do so. Zilmar has worked way too hard to focus on stuff like this when many other things are happening like GLideN64, N64DD stuff, etc.

Compiling Project64 isn't hard, just load up Visual Studio and point to the solution file and hit build.

I'm sure Zilmar is considering everybody when he makes decisions. But obviously he has to live too.

Put yourself in his shoes.

**Comment by cxd4** [comment]
nvm, it was a symbol collision issue with the Linux build :)

re above post, I somewhat doubt he's even doing it for the money itself since the cents that come through installing the adware is less than he'd ever have by just putting up porn ads somewhere as well as things even less morally sensible to him than the "infection" is to everyone else.  Besides if the adware in the installer was for the purpose of money then he wouldn't have taken down the donations system unnecessarily and just left it open as a possible alternative to running the installer--why replace one source of income with another when having both was no trouble?

If not to get more money why he does it then, I really don't know or care because like vgturtle said it's no trouble at all to just compile Project64, except for the trouble with installing Visual Studio, but that's a one-time thing as long as you have more than enough disk space for it.

**Comment by JunielKatarn** [comment]
@vgturtle127 @cxd4 We should think beyond our preferences and expertise.
I myself could use the installer and carefully avoid the adware. Our small developer community is not who is at risk, but the end user who likely doesn't know how to build the source neither distinguishes a scammy adware installation offer: the end user.

PLEASE, do not pull the Ra's Al Ghul-style argument: "If they can't notice and avoid the crapware, they deserve it".

My point is: while its very easy for us to 'just compile' the thing ('just cumpile' = acquiring and installing Visual Studio which is over 2GB download and over 4GB installation), most users won't be able to / willing to, and they shouldn't be expected to.

@project64 , I'd like to bring you into the discussion at this point. Don't you think our arguments are valid? Removing the adware would very likely increase the download rate and trust of Project 64.
Can we explore alternate ways of ads and revenue to support your work and the project?

At the very least, can you please make a final statement, if there is one?

**Comment by cxd4** [comment]
> @vgturtle127 @cxd4 We should think beyond our preferences and expertise.

um, no u?

>My point is: while its very easy for us to 'just compile' the thing ('just cumpile' = acquiring and installing Visual Studio which is over 2GB download and over 4GB installation), most users won't be able to / willing to, and they shouldn't be expected to.

Well that's actually a matter of your own preferences and expertise, because this "developer community" isn't so small as you put it.  Project64 has had tens of contributors--probably hundreds if you count touching merely the support files.  I'm not even sure that I would consider myself to be one of them compared to the contributions made here by plenty others.

Probably end users want us to be arrogant and competitive, if nothing else would benefit.  They want us to feel elite enough to keep the crew of development/source control only between a select few of us, keep them out of it, and push them into the binary-only releases just like they want.  Wanting your users to be happy with only working with binary releases, never your sources or source releases, is simple elitism and/or arrogance.  If they're stubborn then that's on them, not you.  I'd say if you have nothing better to be proud of, then go ahead and make users rely on binary releases all the time.  It's exactly how Microsoft has secured their control over how nearly all the world has been raised to software:  Make them dumb, just like you want. :) Oh sorry you said no anti-Windows fanboyism.  Too bad because with these posts you practically beg the relevance of it.

**Comment by vgturtle127** [comment]
@cxd4 Yeah, it couldn't be making that much money. Especially since most ad companies really cut you out of the whole deal (I should know since I upload YouTube videos) :unamused: 

@JunielKatarn I wasn't saying that. I understand most users will not be knowledgeable enough to compile software. They could still run the installer with /noads though. But I totally get what you're saying. We all have to start somewhere. :smile: 

@cxd4 I don't think adding ads to an installer means anybody on the Project64 team is trying to push binary elitism and restrict the source. I think Zilmar is just trying to recoup some of the cost of having the website, forums, etc. Project64 use to be closed and cost money. Now that it isn't, I think it would be hard to do that since everything is open now. Once it is open, it pretty much stays that way. And it is GNU GPLv2, so any change like that would break the license.

More on topic, I think adding donations and a zip release should quiet this whole thing down. I would definitely donate a few dollars. :smiley:

**Comment by cxd4** [comment]
> I understand most users will not be knowledgeable enough to compile software.

I don't think that "knowledgeable" is the keyword there.

Not knowing how to compile software is about the same as not knowing how to configure some emulation plugin you want to use:  In the bottom case you would probably have just Google'd it.  Don't know how to burn an ISO?  You would find out and install some program and figure out what menu command burns it.  Don't know how to compile a C source file?  It's no different.  The VS IDE is all the same as any other type of chore you have to figure out on any system; the word "compile" is just some frightening thing to people who are more comfortable with the unknown.

Some people just have a fear of the unknown being solved.  Maybe they feel more nostalgic by magically pretending that compiling software is some kind of skill that's for the elite and not them.

> @cxd4 I don't think adding ads to an installer means anybody on the Project64 team is trying to push binary elitism and restrict the source.

No no, you invert where I was coming from with that.

It's quite the opposite.  Making the installer undesirable or unusable does NOT push binary elitism and restrict the source.  You didn't think that was the point I was trying to make, did you?  How does "forcing" people to have to compile sources in order to get the software push binary elitism on the users?

I'm saying that there is a bigger comparison at hand here.  The complaints about what happens when you run the installer without /noads or whatever on the command line are far louder than any complaints about the project not being open-source and requiring the **opposite** of that:  using the installer or having binary-only releases pushed on them.

>Project64 use to be closed and cost money. ... I think adding donations and a zip release should quiet this whole thing down. I would definitely donate a few dollars.

You just acknowledged right there that Project64 had a donations system (which you refer to as "cost money").  That was how things were done back then; to get 1.7 you had to donate $20 or $15 or something, not sure.  You repeatedly present the idea of "adding donations" in the form as if it wasn't done before, yet you just acknowledged that it's already been tried in the past.  Of course you correctly say "cost money" because "donations" was just a legalese workaround from the reality.

**Comment by vgturtle127** [comment]
@cxd4 Haha, I see what you were saying now. Oops.

Well, I think there is a difference between what I mean by donations and what use to be donations on Project64. Donations should be optional and voluntary. That's why it is a donation. With the old 1.7/1.6/whatever you had to donate in order for you to download it. That's why I said it like that. It really wasn't a donation if you are forced into donating to get a product. That's called a purchase. Which, at least in my opinion, should never be done when it comes to emulators. For both preservation and for many more reasons (Android emulators do this with GPL software all the time and it makes me sad :disappointed: ).

I can see both sides of this argument. Fortunately, I have never had to deal with ads or monetization of anything emulation-related due to the fact that next to nobody downloads anything I make (maybe a good thing?). I wish there was a compromise we could make. Unless that is what we're suggesting, but I don't know. I'm just a developer. :fearful:

**Comment by aschwant** [comment]
This may not be viable on several levels, but an idea I've had in the past is "selling" game saves. Sure, you can find them online, but I would pay a dollar or two for a save knowing it was helping pj64 rather than look around on the web - especially if it was available through the library gui. Plus it would be useful for developers to have a library of saves for replicating bugs. I'm not sure about legal implications though.

**Comment by utterbull** [comment]
@aschwant I'm almost positive there are some prohibitive legal implications there.

**Comment by cxd4** [comment]
It sounds interesting, but I think you may as well sell INI files/registry keys.

**Comment by vgturtle127** [comment]
Unfortunately in the US that would be considered distributing copyrighted material. :person_frowning:

**Comment by utterbull** [comment]
Seeing as Zilmar can't be bothered to post, I move that we get merge the request.

**Comment by JunielKatarn** [comment]
So do I! However, is that even possible? We do need someone with write-access to the main repo.

**Comment by cxd4** [comment]
zilmar has write access to the main repo.  Was that what you meant?

**Comment by JunielKatarn** [comment]
I meant "We do need someone with write-access to the main repo". Like zilmar, who won't even respond to these posts. I don't know how this request can be merged into the main repo otherwise.

**Comment by cxd4** [comment]
So are we thinking about a bypass strategy to merge the pull request without the repo owner's permission?

**Comment by utterbull** [comment]
@cxd4 At this point, yes.

**Comment by AmbientMalice** [comment]
@utterbull Doesn't work that way. Any of us could fork PJ64 and invite pull requests -- but Zilmar controls the PJ64 website and ultimately he's the go-to coder for PJ64. Good luck getting anywhere without him. Project 64U "Bane Edition" would be funny, but ultimately kinda useless.

**Comment by Rukario** [comment]
That doesn't sound too bad. We can move on to "Project 64U" and even start a website for it where it is more flexible toward developers and we will be more happier that way. Then Zilmar can move on and catch up with his real life stuff or whatever.

**Comment by LegendOfDragoon** [comment]
>Doesn't work that way. Any of us could fork PJ64 and invite pull requests -- but Zilmar controls the PJ64 website and ultimately he's the go-to coder for PJ64. Good luck getting anywhere without him.

This is indeed true.

**Comment by vgturtle127** [comment]
I don't think we need a separate project just to get rid of ads. Even if @project64 doesn't want to get rid of them. Another build perhaps, but not a separate project.

**Comment by Rukario** [comment]
Not only for getting rid of ads but also let other developers have rights to merge and others that Zilmar wouldn't normally let them to.

I also wonder what does "U" stand for in "Wii U".

**Comment by vgturtle127** [comment]
@Rukario Hey, I never thought of that. What DOES the U in Wii U stand for? :confounded:

**Comment by cxd4** [comment]
Not a bad idea Rukario.  There should be a repository for Project64 1.4 back when it was still written in a free language like C. :) That truly would be portable and more active to improvements.

>

@Rukario Hey, I never thought of that. What DOES the U in Wii U stand for? :confounded:

Only like, the very first thought in my head after hearing about a "Wii U".
Anytime I hear that I'm like, um, NO U!  Because that's what the U in Wii U means.

>He is also unwilling to say/do something about this pull request for quite a while...

That's because explaining the installerware is like trying to teach a religion to everyone and convince them all.  I don't even that much care about the explanation; maybe it's because zilmar hates "communism" or whatever, or it's some other deeply, intellectually rooted moral compass of his that opposes free software over payware in general.  Doesn't bother me because they're not my beliefs and because as long as the source is out and can be compiled, it's still free.  And that's exactly the kind of free that the masochist users don't care about--relying on pre-compiled binaries of Project64 is no easier OR better quality release than installing the WDK and running a batch script to link against msvcrt.

**Comment by vgturtle127** [comment]
@cxd4 What do you mean when you say a "free language". Aren't all of them free? Free as in freedom, or free as in free of a certain restriction?

**Comment by cxd4** [comment]
>Aren't all of them free?

It's a nice thought, but Stroustrup didn't seem to think so.
http://www.stroustrup.com/bs_faq.html#Csharp
http://www.stroustrup.com/bs_faq.html#Java

We're talking about the same guy who praised C as the best language of its time, then invented the C++ language and outcasts the practices of C in favor of _"a good language"_ **like** C++.

>Free as in freedom, or free as in free of a certain restriction?

Project64 1.4 is not simply more free than Project64 2.x insofar as choice of programming language--it's also more free than Project64 1.6.  One of the examples is that in pj 1.6 the "game fix" cheats were moved out of the designated CHT file, for reasons of outward appearance and user perspective in the "majority faction".  The quality of free software doesn't appeal to majority; it appeals to correct engineering principles--of which many of the other hacks included after project64 1.4 do not fall under.  This also is the cause of many regressions and RDB notes in 1.6 saying to use 1.4 for some games, none of which can be tested by Git checkouts due to the tarball/SVN convention of keeping source for various reasons.  So in that sense among any other, 1.4 is the most free version.

**Comment by vgturtle127** [comment]
@cxd4 Oh OK. We could still remove the hacks if we patch Project64 2.x with better emulation. And the RDB can also be updated.

I mean, I don't really know how many games and other parts of Project64 need to be updated, but I'm sure it isn't "too late". I'm thinking of starting a branch on my GitHub and trying to improve it as much as possible. It might be a big pull request, or many small ones. Regardless, I still need to get my dev machine out of storage and upgrade it to Windows 10. After that will be when the patches start coming.

Until then, I am trying to make as many contributions I can with GitHub online tools.

**Comment by cxd4** [comment]
_"We could still remove the hacks if we patch Project64 2.x with better emulation."_
Well let's not oversimplify things here.  Clean code comes first.

Ironic as it is, even the guy responsible for C++ existing cares deeply about portability:
http://www.stroustrup.com/bs_faq.html#portability

And those are only _some_ of the relevant issues.  Patching Project64 2.x with better emulation also requires the ability to test for regressions--not only is the vast majority of the 1.4 tarball's compatibility advantage a bunch of untracked unknowns, but the ability to test changes on more than one operating system can both point out unforseen bugs AND accidental improvements to emulation on some platforms, where bad code could actually fix a game when compiled on the right target.  Being Windows only does not help anything there.

**Comment by JunielKatarn** [comment]
The adware. May never be removed from the traditional installer, but I found an alternative.
I've integrated ClickOnce deployment to my continuous integration builds. It's a simplified type of windows installer which can't do weird stuff like writing to the registry or hijacking your browser.

Moreover, it will automatically detect and download updates (when newer builds get published), which is convenient for alpha testers (non developers) and end users.

Take a look and let me know what you think.
http://hyvart.com/download/project64/ci/project64.application

**Comment by vgturtle127** [comment]
So how will your build work? Is it compiled daily to reflect daily updates? Is it stable builds compiled without the adware? I would want to know more information before I just download a random ClickOnce application.

**Comment by JunielKatarn** [comment]
Basically, each time I pull code from the main repo into my fork, the build process will trigger and update/sign the artifacts. So, if you run the application, it will automatically check for updated bits from the source website and download them. And yes, without ANY adware, because ClickOnce takes care of the setup and I don't even pack the infected installer in my distribution.
In short, it will pretty much reflect the latest code from master, so it will be a "bleeding edge" build (FWIW, built with VS2015).

Regarding the 'random' application, hyvart.com is my site, so you can take my word that any content there is safe (I may eventually sign the app, if that helps at all).

**Comment by vgturtle127** [comment]
OK, I am just being cautious. Lots of hacking and malware and stuff going around lately. :fearful:

**Comment by PFCKrutonium** [comment]
This should be merged.

**Comment by JunielKatarn** [comment]
> This should be merged.

@PFCKrutonium It won't, though :disappointed:
If you like, you can try my ClickOnce continuous build. Safe to install, crapware free:
http://hyvart.com/download/project64/project64.application

**Comment by vgturtle127** [comment]
@PFCKrutonium You can use EmuCR builds or you can also use @JunielKatarn 's builds, of course.

But you can also compile them yourself, which is faster and has the added benefit of being able to debug the application as well.

**Comment by cxd4** [comment]
Yeah apparently there is no adware, just directions in the installer to connect online and fetch random surveys to download adware.

Which amuses me because I can't get Internet on this laptop to work with Windows anymore anyway.  Couldn't infect myself even if I tried.

So yeah.  If any of you have internet issues like I do, you're probably wondering wth this PR even is.

**Comment by vgturtle127** [comment]
@cxd4 Oh, I see. You are just having Windows-specific problems then?

I would think by now most people would know not to click ads in installers...But then again Internet Explorer security issues along with Java and Flash is still a huge problem, so I guess it will always be like that. :laughing:

**Comment by GB-CG** [comment]
Is this still a thing? (Screenshot is taken from Chrome OSX)


 I thought it was fixed a while ago..? Then again, I'm on OSX so I don't really get junkware on my end.

**Comment by PFCKrutonium** [comment]
It is indeed still a thing.

**Comment by JunielKatarn** [comment]
@GB-CG You can download a up to date build at http://hyvart.com/download/project64/ci/, or use a crapware-free installer at http://hyvart.com/download/project64/project64dev.application.

**Comment by GB-CG** [comment]
@JunielKatarn Thank you. But for OSX, v2.2 settings pane still yet to be fixed by WineHQ, so I'll just stick with v2.1 and below. But thanks anyway.

**Comment by Rukario** [comment]
It's happening! Thank you, really.

**Comment by crazyboy92** [comment]
WHAT THE HELL WERE YOU THINKING WHEN YOU PUT ADWARE IN THE INSTALLER BACK IN 2013!? THE DAMAGE WAS ALREADY DONE!! I'M NEVER DOWNLOADING PROJECT64 2.3 WHEN IT COMES OUT SINCE I DON'T TRUST NEW VERSIONS ANYMORE!! I'M STILL PISSED OFF WHEN PEOPLE HAD VIRUSES FROM THE INSTALLER!! JABO DIDN'T WANT TO BE HELD RESPONSIBLE FOR THAT!! I'M AVOIDING PROJECT64 VERSIONS 2.X LIKE THE PLAGUE NOW!!! SHIT!!! WHAT THE HELL WAS THIS DECADE GOOD FOR ANYWAY!? WHY BAD THINGS HAPPEN DURING THE FIRST HALF!! THIS DECADE WAS HORRIBLE!!! WAS KARMA A BITCH!? NOBODY WAS STILL HAPPY ABOUT IT WHEN MALWARE WAS REMOVED IN THE INSTALLER!! THE 2.X VERSIONS WAS NOTHING BUT A BETA JUST LIKE VERSION 1.7.0.50 WHICH WAS ALSO A BETA!! I SHALL NOT FORGIVE ANYONE FOR PUTTING A MALWARE IN THE INSTALLER AS SUCH!!! SHIT!!! MUPEN64PLUS NEEDS AN OFFICIAL GUI!!! I'M NEVER USING PROJECT64 AGAIN!!! I'M DELETING MY ACCOUNT AFTER THIS POST TOMORROW!!! GOODBYE!!! I HATE YOU ALL!!! THIS DECADE SUCKED!!! YOU CAN KEEP YOUR FUCKING MALWARE IN THE INSTALLER!!!

**Comment by MELERIX** [comment]
@crazyboy92

**Comment by oddMLan** [comment]
>

WHAT THE HELL WERE YOU THINKING WHEN YOU PUT ADWARE IN THE INSTALLER BACK IN 2013!? THE DAMAGE WAS ALREADY DONE!! I'M NEVER DOWNLOADING PROJECT64 2.3 WHEN IT COMES OUT SINCE I DON'T TRUST NEW VERSIONS ANYMORE!! I'M STILL PISSED OFF WHEN PEOPLE HAD VIRUSES FROM THE INSTALLER!! JABO DIDN'T WANT TO BE HELD RESPONSIBLE FOR THAT!! I'M AVOIDING PROJECT64 VERSIONS 2.X LIKE THE PLAGUE NOW!!! SHIT!!! WHAT THE HELL WAS THIS DECADE GOOD FOR ANYWAY!? WHY BAD THINGS HAPPEN DURING THE FIRST HALF!! THIS DECADE WAS HORRIBLE!!! WAS KARMA A BITCH!? NOBODY WAS STILL HAPPY ABOUT IT WHEN MALWARE WAS REMOVED IN THE INSTALLER!! THE 2.X VERSIONS WAS NOTHING BUT A BETA JUST LIKE VERSION 1.7.0.50 WHICH WAS ALSO A BETA!! I SHALL NOT FORGIVE ANYONE FOR PUTTING A MALWARE IN THE INSTALLER AS SUCH!!! SHIT!!! MUPEN64PLUS NEEDS AN OFFICIAL GUI!!! I'M NEVER USING PROJECT64 AGAIN!!! I'M DELETING MY ACCOUNT AFTER THIS POST TOMORROW!!! GOODBYE!!! I HATE YOU ALL!!! THIS DECADE SUCKED!!! YOU CAN KEEP YOUR FUCKING MALWARE IN THE INSTALLER!!!

ok

**Pull request merged**
