### PR TITLE
Update several support files

### PR DESCRIPTION
**Pull request by Fanatic-64**
Update several non-source files, including:
-Documentation
-A newer CHT
-Jabo 1.6.1 plugins (instead of 1.6)
-N-Rage 1.83 (instead of 1.82a)

### CODE REVIEW

**Comment by Fanatic-64** [comment]
Don't know how to make both commits into separate pull requests...

**Comment by death-droid** [comment]
Have to keep changes separated into individual branches.

**Comment by Fanatic-64** [comment]
Will do... next time. Don't know how to roll back commits either.

**Comment by blikblum** [comment]
Create a branch from a previous commit http://stackoverflow.com/questions/2816715/branch-from-a-previous-commit-using-git
Cherrypick the commit into this branch https://ariejan.net/2010/06/10/cherry-picking-specific-commits-from-another-branch/
Create a new pull request from the branch

**Comment by project64** [comment]
where is the source of the binary files from? I pushed a change for the 400 ai

**Comment by Fanatic-64** [comment]
You mean where I got them from? Well, here's were I got all the files from:
-PJ64gameFAQ.chm, RDB - WhatsNew.txt: Obtained from here: http://www.pj64-emu.com/downloads/func-startdown/109/
-Project64.cht: Obtained from this commit: https://github.com/project64/project64/tree/e815584b593d2b2c715a89b8a7d4321c8c1106ce
-NRage_DInput8_V2.dll, N-Rage - Readme.txt: Obtained from here: http://members.chello.at/n-rage/dinput8/index.html Source code is available there.
-Jabo_Direct3D8.dll, Jabo_Dsound.dll, Jabo_DInput.dll: Obtained from here: http://www.jabosoft.com/articles/114

**Comment by Fanatic-64** [comment]
Is this going to be merged? I need to delete and recreate my fork since I messed a bit with GitHub.

**Comment by LegendOfDragoon** [comment]
Why delete?

**Comment by Fanatic-64** [comment]
"and recreate my fork since I messed a bit with GitHub"

**Comment by LegendOfDragoon** [comment]
You're likely able to fix it without having to delete ;/ . You can edit commit history. To make your fork up to date, just use type the following, into git shell
cd project64
git pull https://github.com/project64/project64.git in the git cmd.

**Comment by cxd4** [comment]
That would pull the current state of `project64/project64.git` to his local hard disk yes, but it wouldn't revert the commits already uploaded to `Fanatic-64/project64.git` to his online account.

I've deleted and re-forked Project64 repository 3 times already and guess I didn't see any negative effects from it.  I had to delete and re-fork whenever a pull request I sent got declined, and force-overwriting master branch when pushing failed 90% of the time due to my crappy network Wi-Fi.

**Comment by project64** [comment]
ok I think that has everything from this pull request now has bee updated or removed from the release.

**Comment by Fanatic-64** [comment]
Could we include the newer RDB - WhatsNew.txt file? Or remove it from the repo?

**Comment by project64** [comment]
there has been a lot of updates to the rdb lately .. what in particular do you want in there ?

yes some of these files can probably removed from the current branch.

**Comment by oddMLan** [comment]
Where is the newer .cht file from? Is that update going to be included in master repo?

**Comment by project64** [comment]
as Fanatic-64 comment, I got it from https://github.com/project64/project64/tree/e815584b593d2b2c715a89b8a7d4321c8c1106ce it is now in the config dir

**Comment by death-droid** [comment]
Can be closed now?

**Comment by project64** [comment]
I suspect we can, I removed the old files that will not be in 2.2, the change to the settings config is in as well as I think all files that were updated.

**Pull request closed without merging**
