### PR TITLE
Add Discord RPC

### PR DESCRIPTION
**Pull request by shygoo**
Shows what game you're playing in Discord. Not enabled by default. (Addresses #1494)

screenshot
screenshot

### CODE REVIEW

**Comment by Frank-74** [comment]
Tested and is working perfectly.

**Comment by NailNatail64** [comment]
Tested and still working perfectly when i used this as a base to code it into my 2.3.2

**Comment by NailNatail64** [comment]
You should maybe scrap box art and possibly show on the RPC what menu you are in.

**Comment by loarca** [comment]
is this feature still going on?

**Comment by CrankySupertoon** [comment]
I was working on it I push a PR soon

**Pull request closed without merging**
