### PR TITLE
Removed nagware from the Windows interface

### PR DESCRIPTION
**Pull request by Clownacy**

### CODE REVIEW

**Comment by CrashOveride95** [comment]
Why though

**Comment by theboy181** [comment]
Less work to just donate to an awesome emulator developer. Happy Xmas zilmar!

**Comment by CrashOveride95** [comment]
I have no issue with the nagware, don't see why it needs to be removed

**Comment by theboy181** [comment]
image
So sad

**Comment by cxd4** [comment]
I buy Himalayan pink salt.

Has the following benefits over white table salt:

* pricier but mined from the Himalayas where warm sea water (for sea salt) mercury contamination is out of the question
* more mineral nutrients and more _of_ them with pink salt than white salt
* stronger concentration of flavor per unit of Himalayan salt per less sodium consumed...so harder to exceed daily recommended sodium intake when getting the same flavor

Iodized sea salt may be the next best thing if you can't afford the pink salt, but water is contaminated with inorganically present minerals all the same, even if you buy it purified inside some cheap plastic bottle off the store shelf.  So just buy a home distiller...or reverse osmosis purifier may be cheaper if you're one of those opponents of drinking distilled water.

**Pull request closed without merging**
