### PR TITLE
Line ending and File-encoding update.

### PR DESCRIPTION
**Pull request by MelchiorGaspar**
PLEASE I hope i got this Branch HELL right this time ;^_^;

### CODE REVIEW

**Comment by cxd4** [comment]
You did it fine.  Don't worry anymore; you followed my instructions closely enough.

**Comment by project64** [comment]
I have no issue with this, but what effect does this actually have?

**Comment by MelchiorGaspar** [comment]
just cleaning up I guess they had the old file encoding
the .props files had LF Linux line ending


and the .vsprops had these file encoding  both for the xml header and the file it self...
UTF-8 is the current good standard...  
Windows-1252 is ancient, Latin file encoding and
Windows-1251, is Cyrillic script such as Russian, Bulgarian, Serbian Cyrillic and other languages.
 
.

**Comment by MelchiorGaspar** [comment]
Consistent file encoding.

**Pull request merged**
