### PR TITLE
Multiplayer timing fix for E and J regions

### PR DESCRIPTION
**Pull request by Nekokabu**
Add Mario Kart Multiplayer timing fix cheat for E and J regions.

### CODE REVIEW

**Comment by loganmc10** [comment]
Are the E and J versions really the same? How were these calculated?

**Comment by loganmc10** [comment]
Also these are half the size of the U version. Does this fix 2 and 3/4 player?

**Comment by Nekokabu** [comment]
>Are the E and J versions really the same? How were these calculated?

Original code? is here: http://tasvideos.org/GameResources/N64/MarioKart64/Patches.html
I disassemble and compare them.

>Also these are half the size of the U version. Does this fix 2 and 3/4 player?

Unnecessary code was deleted, so it got shorter. 
Including 2 and 3/4 player fix

**Comment by Nekokabu** [comment]
https://github.com/project64/project64/pull/607

**Pull request merged**
