### PR TITLE
Plugin code cleanup

### PR DESCRIPTION
**Pull request by death-droid**
Implement @Twostars cleanup of the plugin system, makes all plugin (RSP,AUDIO,GFX and CONTROLLER) derive functions from a singular class. Cleans up the code significantly and removes the need to have duplicate code in every seperate plugin file that does the same thing. Should also make it much easier to modify and add new specifications that apply to all plugins.

### CODE REVIEW

**Comment by project64** [comment]
ok created a branch that mast most of this functionality, have a look at it, if your happy with it I will merge that branch and close this pull request

**Comment by death-droid** [comment]
Looks all good to me!

**Comment by death-droid** [comment]
Just need to add plugin base.cpp and plugin base.h to Visual studio 2013 project file

**Comment by project64** [comment]
Ok merged the code

**Pull request closed without merging**
