### PR TITLE
Update French.pj.Lang

### PR DESCRIPTION
**Pull request by BenjaminSiskoo**
Small typos fixes + add new strings from the English language

### CODE REVIEW

**Comment by cxd4** [comment]
pinging @Watilin for possible language feedback

**Comment by BenjaminSiskoo** [comment]
Misunderstanding :) I just added some missing strings from the English file to the french file (le g : detect key) ^^

**Comment by cxd4** [comment]
Sounds good to me.  I don't know French.

It just seemed a couple strings were being modified, not added, and either way I figured Watilin (being one of the French language contributors) might have liked to keep informed about it anyway.

**Comment by BenjaminSiskoo** [comment]
No problem :)

**Comment by Watilin** [comment]
> might have liked to keep informed about it anyway.
That’s nice of you :)

I noticed some minor adjustments I could do. French uses many less capital letters than English. I’ll make a PR.

**Pull request merged**
