### PR TITLE
Linux build and chrome os build via linux terminal

### PR DESCRIPTION
**Pull request by PaperVb64**
Developing the Project64 for another platform could be hard (and most likely a pain in the a**), but could you at least try for linux? Also, could you develop for chrome OS? It doesn't have to be for the MAIN operating system as an app, but as a .deb for use when Linux apps is installed? If you can, thanks a lot!

### CODE REVIEW

**Comment by CrashOveride95** [comment]
why did you make what looks like an issue, a pull request

**Comment by ariahiro64** [comment]
this pr is so messed up its actually impressive in the wrong ways

**Comment by oddMLan** [comment]
Average linux user

**Comment by ghost** [comment]
i love this pr

**Comment by PaperVb64** [comment]
this is a suggestion, not an issue.

**Comment by ghost** [comment]
> this is a suggestion, not an issue.

okay, but this isn't a code contribution either. suggestions are usually issues on github. stop being an eta kid. if you'd really like to emulate the n64 on linux use mupen.

**Comment by project64** [comment]
this is not a pull request that can be merged

**Comment by PaperVb64** [comment]
does mupen have the same features tho

**Comment by LegendOfDragoon** [comment]
> does mupen have the same features tho

Nope.

**Pull request closed without merging**
