### PR TITLE
Add some ALECK64 games to the RDB

### PR DESCRIPTION
**Pull request by LegendOfDragoon**

### CODE REVIEW

**Comment by theboy181** [comment]
Were you able to get Zoinkity to commit to internal names for his patches?

**Comment by LegendOfDragoon** [comment]
>Were you able to get Zoinkity to commit to internal names for his patches?

Haven't spoken to him about it. I guess internal name isn't too important ;/ .

**Comment by Predator82Germany** [comment]
What´s the difference to ALECK64?

**Comment by cxd4** [comment]
Nice commits

**Comment by cxd4** [comment]
No shouldn't change the internal game title field to the ROM header, or add one.

**Comment by theboy181** [comment]
yes, thanks @LegendOfDragoon

**Pull request merged**
