### PR TITLE
Build fixes for Visual Studio 2013

### PR DESCRIPTION
**Pull request by death-droid**
Build fixes for Visual Studio 2013

### CODE REVIEW

**Comment by cxd4** [comment]
Like the first and third commits.  The ads EXE just seems like something that could be distributed in the public download for people who would rather go through that than compile (though I'm not sure if zilmar would agree to having that file removed).

The middle one is mostly a lot of added files I guess--it was a pain in the ass for me to find out how to downgrade to MSVC 2008 to compile this, though at the same time I'm not sure how I'd feel in zilmar's position about having both the VS2008 and VS2013 project files co-sharing the same repo space.  Maybe it depends how much individual work had to be done manually to produce/convert into those files.

**Comment by project64** [comment]
I want to play with this on visual studio 2013 first, I might get a chance to do that next week

**Comment by death-droid** [comment]
Fairly sure Zilmar changed it so it no longer uses that ads exe.

It's adding all the project files for Visual Studio 2010+, all previous project files for 2008 is still there and i have no deleted them.
Ok good to hear Zilmar, theres also the Community version of Visual Studio now, havent tried it myself but it should work with the project files included on here.

**Comment by death-droid** [comment]
Annoyingly enough I can't seem to submit a separate pull request for my other changes without it wanting to bring these with it :\

**Comment by oddMLan** [comment]
It's usual practice to create a new branch for each set of related changes you want to submit. In this case, you're merging your commits from your master repo, which can be annoying cuz every other change you make will be added in this pull request. You can save yourself a lot of time if you create a branch like "deathdroid:vs-2013-build-fixes" and then submit your related commits to that branch.

**Comment by death-droid** [comment]
Hmm yeah that's what I've started doing :+1: Though for now there all stuck with this pull. Unless i delete the fork again and start clean again >.<

**Comment by project64** [comment]
you can probably make a branch from an earlier commit, then update it from another stream (main project64 branch). Then just cherry pick individual changes.

**Comment by death-droid** [comment]
Hmm I could, but then can't compile because i lose my changes to compile it under Visual Studio 2013.
Might just have to hold out on them till you can test and pull in this.

**Comment by death-droid** [comment]
Clossing pull so i can handle this better on my side. Im quite terrible with this git stuff

**Pull request closed without merging**
