### PR TITLE
Instantiate fixed-size standard int types to core CPU.

### PR DESCRIPTION
**Pull request by cxd4**
Previously we have applied the C99 standard integer types to the RSP plugin.
https://github.com/project64/project64/pull/146

I mostly started just with the RSP plugin since it was smaller, less code, written in C, easier to work with...but I do encourage anybody in control of this project's future to continue my efforts for me to get rid of the WINAPI types for tasks pertinent to N64 emulation.  (If it's something related to the Windows operating system, such as memory management for re-compiler voodoo and sorcery, then it might have to stay stuck with the `windows.h` types.)  Not only will these efforts result in more readable code and types (DWORD on Intel is not a MIPS DWORD.) but also in anyone's chances of continuing development outside of a Microsoft environment.

This pull request again, as in the case of the last one for my RSP changes, is not a complete change to all the types in all of the code.  I just did the interpreter CPU, which I think is the most important part of the emulator in all aspects (portability being just one).  Again I encourage anyone to continue these sorts of changes to the rest of pj64 or the RSP.

### CODE REVIEW

**Comment by cxd4** [comment]
Conflicts resolved. :/

**Comment by cxd4** [comment]
> This pull request contains merge conflicts that must be resolved.

Hah.  Just killed my own pull request by centralizing the code for overwriting $zero.  None of those lines I deleted even had stdint.h types in them, so where Git keeps getting these conflicts from is beyond me.

**Comment by MELERIX** [comment]
I think is because you don't have synchronized you master repo with this one.

for example your master repo (https://github.com/cxd4/project64/) says: This branch is 235 commits behind project64:master

**Comment by cxd4** [comment]
Actually I killed it with my own pull request from before.  I modified lines adjacent to the lines I modified in these commits, which evidently caused a "conflict" (however the hell that works...).

I could just do what I did earlier and settle the merge conflicts using a massive series of Git commands, but I don't see the point in bothering with that unless @project64 was intent on just merging the changes in this PR rather than manually committing them on his own machine.  Personally, I don't see any room for doubt that any of these changes could possibly break anything, due to the clear equivalence of the types I have written here, so I can only guess what is so confusing about just merging it.  I guess it's because most of the remaining source to Project64 needs these changes as well, and zilmar doesn't want to merge this because it's inconsistent with the massive rest of the source which could also want these changes.

**Comment by uyjulian** [comment]
Learn to use the git command line...
cd project64 && git pull https://github.com/project64/project64.git
git will tell you the conflicts

**Comment by cxd4** [comment]
>Learn to use the git command line...

@uyjulian : Learn to read what people have been doing the entire time.  Never use GUIs for this.

Exactly how do you think I succeeded in solving the merge conflicts with this pull request the last time I used the command line?  Does your native language cause you to miss the part where I just said that I'm **choosing** not to bother fixing the new merge conflicts if zilmar isn't intent on directly merging the commits anyway?  I mean, why waste anyone's time?

Furthermore I already know exactly what the conflicts are, because I deliberately made the pull request that broke this one.

**Comment by uyjulian** [comment]
whoops, missed that part.
I thought you meant you don't know how to rebase easy.

**Comment by cxd4** [comment]
For the sake of practice and experiment, I've also gone ahead to resolve merge conflicts here as well.

Though it seems my experiment was only partially successful, as it forced me to add an extra commit of mine to RSP Allman changes that I held back for doing later in a separate PR.

**Comment by cxd4** [comment]
Change of plans as portability outside of Windows is best organized to a separate branch fork.

**Pull request closed without merging**
