### PR TITLE
[PJGlide64] imul16: no need for inline asm here

### PR DESCRIPTION
**Pull request by cxd4**
Recreated from old pull request dead from merge conflict:  https://github.com/project64/project64/pull/502.

### CODE REVIEW

**Comment by JunielKatarn** [comment]
Please, do not submit crappy changes. This breaks compilation:

"D:\p64\repo\Project64.vs2013.sln" (rebuild target) (1) ->
"D:\p64\repo\Source\Glide64\Glide64.vcxproj" (Rebuild target) (8) ->
(Link target) ->
  DepthBufferRender.obj : error LNK2019: unresolved external symbol _imul16 referenced in function "void __cdecl LeftSection(void)" (?LeftSection@@YAXXZ) [D:\p64\repo\Source\Glide64\Glide64.vcxproj]
  DepthBufferRender.obj : error LNK2019: unresolved external symbol _imul14 referenced in function "void __cdecl LeftSection(void)" (?LeftSection@@YAXXZ) [D:\p64\repo\Source\Glide64\Glide64.vcxproj]
  D:\p64\repo\Plugin\GFX\PJ64Glide64_d.dll : fatal error LNK1120: 2 unresolved externals [D:\p64\repo\Source\Glide64\Glide64.vcxproj]

    3 Warning(s)
    3 Error(s)

**Comment by JunielKatarn** [comment]
@project64, please revert this change. It breaks the build.

Note: build was tested with this command:
MSBuild.exe .\Project64.vs2013.sln /t:rebuild

**Comment by cxd4** [comment]
>This breaks compilation:

That's a linker error, not a compilation error.

Please, do not submit crappy "regression" reports.  If you have anything of validity to say of the actual changes I made to the functions, then please say that.  Otherwise, it's clear that the point was to convert the inline asm to standard C code, which plainly was successful.

**Comment by cxd4** [comment]
finished the rest of the fix in https://github.com/project64/project64/pull/506

**Pull request merged**
