### PR TITLE
Minor Updates for package_zip.bat

### PR DESCRIPTION
**Pull request by MELERIX**
- Output directory will be cleaned before start to copy files.
- Removed copy line for two .chm files that are outdated.
- Added copy line for a plugin that was missing.

### CODE REVIEW

**Comment by project64** [comment]
looks fine except I was keeping Jabo_DInput.dll out on purpose to make sure the nrage plguin was good enough to replace jabo's.

I would prefer to use an open source plugin we can support and modify.

**Comment by MELERIX** [comment]
I see, then Jabo_DInput.dll should be removed from installer.iss too ?

**Comment by project64** [comment]
yes, I was planning to go back to the installer when I was getting closer to release and making sure it matches the output of package_zip

**Comment by MELERIX** [comment]
ok, I'll make a new pull.

now closing this one.

**Pull request closed without merging**
