### PR TITLE
Recompiler allman fix

### PR DESCRIPTION
**Pull request by ExtremeDude2**
Got tired of doing this, this is all I'm going to do for now (sorry about the large number, I was just trying to go by folders and I guess it was way more than I thought)
Edit: do not commit this

### CODE REVIEW

**Comment by ExtremeDude2** [comment]
Well this didn't do what I thought, plz do not merge (unless you want to revert a lot of stuff XD)

**Comment by ExtremeDude2** [comment]
I'll leave this here anyway so people can see what I did if they want to continue I guess. (Fell free to close it if you don't want to see it with the rest of the PRs)

**Comment by death-droid** [comment]
Are you doing this all by hand or?
You can actually get Visual Studio to reformat a doccument style to allman with a few tweaks to the settings. Only thing it doesnt seem to change is one line functions.

**Comment by ExtremeDude2** [comment]
I did by hand because I'm dumb

**Comment by ExtremeDude2** [comment]
oh hey, I can close this

**Comment by cxd4** [comment]
orly

**Comment by death-droid** [comment]
Na rly


Sent from my Samsung GALAXY S5

-------- Original message --------

**Comment by cxd4** [comment]
noice!

**Pull request closed without merging**
