### PR TITLE
[Project64-Audio] Remove FAT from audio plugin.

### PR DESCRIPTION
**Pull request by Frank-74**
Fixes main.cpp error.  Caused by FAT being read from Project64.rdb instead.

### CODE REVIEW

**Comment by Frank-74** [comment]
Shall I close this PR and just comment out the offending line that reads FAT from Audio.rdb?

At moment without this PR, Project64 doesn't run because of audio plugin looking for FAT in Audio.rdb.
There's error in main.cpp on starting Project64.exe.

Maybe there should be extra error checking inside plugin, as error in main.cpp makes you think it's problem with project64.exe, not a plugin.

**Comment by LuigiBlood** [comment]
This needs to be taken care of.

**Comment by project64** [comment]
I am fine to merge it you want it in

**Comment by oddMLan** [comment]
Yes, Project64 fails to start otherwise.

**Pull request merged**
